//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgesRange
    {
        public int daID { get; set; }
        public string daN { get; set; }
        public byte daFrom { get; set; }
        public byte daTo { get; set; }
        public byte daO { get; set; }
        public bool daA { get; set; }
    }
}
