//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class allGifts
    {
        public string giID { get; set; }
        public string giN { get; set; }
        public bool giWPax { get; set; }
        public decimal giPrice1 { get; set; }
        public decimal giPrice2 { get; set; }
        public decimal giPrice3 { get; set; }
        public decimal giPrice4 { get; set; }
        public int giMaxQty { get; set; }
        public bool giAmountModifiable { get; set; }
        public decimal giPublicPrice { get; set; }
        public decimal giPriceMinor { get; set; }
        public decimal giPriceExtraAdult { get; set; }
    }
}
