//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class AssistanceData
    {
        public string asPlaceType { get; set; }
        public string asPlaceID { get; set; }
        public System.DateTime asStartD { get; set; }
        public System.DateTime asEndD { get; set; }
        public string aspe { get; set; }
        public string peN { get; set; }
        public string asMonday { get; set; }
        public string asTuesday { get; set; }
        public string asWednesday { get; set; }
        public string asThursday { get; set; }
        public string asFriday { get; set; }
        public string asSaturday { get; set; }
        public string asSunday { get; set; }
        public Nullable<byte> asNum { get; set; }
    }
}
