//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeTo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChargeTo()
        {
            this.GiftsReceipts = new HashSet<GiftsReceipt>();
            this.GiftsReceiptsDetails = new HashSet<GiftsReceiptDetail>();
            this.GiftsReceiptsLogs = new HashSet<GiftsReceiptLog>();
            this.InvitationsGifts = new HashSet<InvitationGift>();
        }
    
        public string ctID { get; set; }
        public byte ctPrice { get; set; }
        public string ctCalcType { get; set; }
        public bool ctIsCxC { get; set; }
    
        public virtual ChargeCalculationType ChargeCalculationType { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsReceipt> GiftsReceipts { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsReceiptDetail> GiftsReceiptsDetails { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsReceiptLog> GiftsReceiptsLogs { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvitationGift> InvitationsGifts { internal get; set; }
    }
}
