//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class CxCData
    {
        public int grID { get; set; }
        public string grNum { get; set; }
        public string grls { get; set; }
        public Nullable<int> grgu { get; set; }
        public string grGuest { get; set; }
        public System.DateTime grD { get; set; }
        public string grpe { get; set; }
        public string peN { get; set; }
        public Nullable<decimal> grCxCGifts { get; set; }
        public Nullable<decimal> grCxCPRDeposit { get; set; }
        public Nullable<decimal> grCxCTaxiOut { get; set; }
        public Nullable<decimal> CxC { get; set; }
        public Nullable<bool> Authorized { get; set; }
        public Nullable<System.DateTime> grCxCAppD { get; set; }
        public string grAuthorizedBy { get; set; }
        public string grAuthorizedName { get; set; }
        public Nullable<decimal> grAmountToPay { get; set; }
        public Nullable<decimal> grAmountPaid { get; set; }
        public Nullable<decimal> grBalance { get; set; }
        public string Pay { get; set; }
        public Nullable<int> grup { get; set; }
        public string grcxcAuthComments { get; set; }
        public string grcxcComments { get; set; }
        public string Log { get; set; }
        public Nullable<long> Page { get; set; }
    }
}
