//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Efficiency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Efficiency()
        {
            this.Personnels = new HashSet<Personnel>();
        }
    
        public long efID { get; set; }
        public string efsr { get; set; }
        public System.DateTime efDateFrom { get; set; }
        public System.DateTime efDateTo { get; set; }
        public string efet { get; set; }
        public string efpd { get; set; }
    
        public virtual EfficiencyType EfficiencyType { get; set; }
        public virtual Period Period { get; set; }
        public virtual SalesRoom SalesRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personnel> Personnels { get; set; }
    }
}
