//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRateLog
    {
        public System.DateTime elID { get; set; }
        public string elcu { get; set; }
        public System.DateTime elD { get; set; }
        public string elChangedBy { get; set; }
        public decimal elExchangeRate { get; set; }
    
        public virtual Currency Currency { internal get; set; }
        public virtual Personnel Personnel { internal get; set; }
    }
}
