//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class GetMailOuts
    {
        public string guStatus { get; set; }
        public Nullable<System.DateTime> guBookT { get; set; }
        public Nullable<System.DateTime> guPickUpT { get; set; }
        public string guRoomNum { get; set; }
        public string guLastName1 { get; set; }
        public string guFirstName1 { get; set; }
        public decimal guPax { get; set; }
        public bool guCheckIn { get; set; }
        public System.DateTime guCheckInD { get; set; }
        public System.DateTime guCheckOutD { get; set; }
        public string guco { get; set; }
        public string coN { get; set; }
        public string guag { get; set; }
        public string agN { get; set; }
        public bool guInfo { get; set; }
        public bool guInvit { get; set; }
        public bool guBookCanc { get; set; }
        public Nullable<System.DateTime> guInfoD { get; set; }
        public Nullable<System.DateTime> guBookD { get; set; }
        public string guPRInvit1 { get; set; }
        public string peN { get; set; }
        public string gumo { get; set; }
        public string gula { get; set; }
        public bool gumoA { get; set; }
        public string guComments { get; set; }
    }
}
