//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class GiftForReceipts
    {
        public string giID { get; set; }
        public string giN { get; set; }
        public string giShortN { get; set; }
        public bool giWFolio { get; set; }
        public bool giWPax { get; set; }
        public string gigc { get; set; }
        public int giO { get; set; }
    }
}
