//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftsReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiftsReceipt()
        {
            this.CxCPayments = new HashSet<CxCPayment>();
            this.GiftsReceiptsDetails = new HashSet<GiftsReceiptDetail>();
            this.GiftsReceiptsLogs = new HashSet<GiftsReceiptLog>();
            this.GiftsReceiptsPackages = new HashSet<GiftsReceiptPackageItem>();
            this.GiftsReceiptsPayments = new HashSet<GiftsReceiptPayment>();
            this.GuestsPromotions = new HashSet<GuestPromotion>();
            this.InvitationsGifts = new HashSet<InvitationGift>();
        }
    
        public int grID { get; set; }
        public string grNum { get; set; }
        public System.DateTime grD { get; set; }
        public Nullable<int> grgu { get; set; }
        public bool grExchange { get; set; }
        public string grGuest { get; set; }
        public decimal grPax { get; set; }
        public string grHotel { get; set; }
        public string grRoomNum { get; set; }
        public string grpe { get; set; }
        public string grlo { get; set; }
        public string grls { get; set; }
        public string grsr { get; set; }
        public string grWh { get; set; }
        public string grMemberNum { get; set; }
        public string grHost { get; set; }
        public string grComments { get; set; }
        public decimal grDeposit { get; set; }
        public decimal grDepositTwisted { get; set; }
        public string grcu { get; set; }
        public decimal grcxcPRDeposit { get; set; }
        public string grcucxcPRDeposit { get; set; }
        public bool grCxCClosed { get; set; }
        public decimal grExchangeRate { get; set; }
        public string grct { get; set; }
        public decimal grMaxAuthGifts { get; set; }
        public decimal grcxcGifts { get; set; }
        public decimal grcxcAdj { get; set; }
        public string grcxcComments { get; set; }
        public decimal grTaxiIn { get; set; }
        public decimal grTaxiOut { get; set; }
        public bool grCancel { get; set; }
        public bool grClosed { get; set; }
        public Nullable<System.DateTime> grCxCAppD { get; set; }
        public decimal grTaxiOutDiff { get; set; }
        public string grGuest2 { get; set; }
        public string grpt { get; set; }
        public byte grReimpresion { get; set; }
        public Nullable<byte> grrm { get; set; }
        public string grAuthorizedBy { get; set; }
        public Nullable<decimal> grAmountToPay { get; set; }
        public Nullable<int> grup { get; set; }
        public decimal grcxcTaxiOut { get; set; }
        public string grcucxcTaxiOut { get; set; }
        public string grcxcAuthComments { get; set; }
        public Nullable<System.DateTime> grCancelD { get; set; }
        public Nullable<decimal> grAmountPaid { get; set; }
        public Nullable<decimal> grBalance { get; set; }
    
        public virtual ChargeTo ChargeTo { internal get; set; }
        public virtual Currency Currency { internal get; set; }
        public virtual Currency Currency_Deposit { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CxCPayment> CxCPayments { internal get; set; }
        public virtual Guest Guest { internal get; set; }
        public virtual LeadSource LeadSource { internal get; set; }
        public virtual Location Location { internal get; set; }
        public virtual PaymentType PaymentType { internal get; set; }
        public virtual Personnel Personnel_AuthorizedBy { internal get; set; }
        public virtual Personnel Personnel_Host { internal get; set; }
        public virtual Personnel Personnel_PR { internal get; set; }
        public virtual ReimpresionMotive ReimpresionMotive { internal get; set; }
        public virtual SalesRoom SalesRoom { internal get; set; }
        public virtual UnderPaymentMotive UnderPaymentMotive { internal get; set; }
        public virtual Warehouse Warehouse { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsReceiptDetail> GiftsReceiptsDetails { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsReceiptLog> GiftsReceiptsLogs { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsReceiptPackageItem> GiftsReceiptsPackages { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsReceiptPayment> GiftsReceiptsPayments { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestPromotion> GuestsPromotions { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvitationGift> InvitationsGifts { internal get; set; }
    }
}
