//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftInventory
    {
        public System.DateTime gvD { get; set; }
        public string gvwh { get; set; }
        public string gvgi { get; set; }
        public int gvQty { get; set; }
    
        public virtual Gift Gift { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
