//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class GiftsReceiptDetailShort
    {
        public int gegr { get; set; }
        public int geQty { get; set; }
        public string QtyUnit { get; set; }
        public string gegi { get; set; }
        public int geAdults { get; set; }
        public int geMinors { get; set; }
        public int geExtraAdults { get; set; }
        public decimal gePriceA { get; set; }
        public decimal gePriceM { get; set; }
        public decimal gePriceAdult { get; set; }
        public decimal gePriceMinor { get; set; }
        public decimal gePriceExtraAdult { get; set; }
        public string gect { get; set; }
        public string geCxC { get; set; }
        public decimal geCharge { get; set; }
        public string geFolios { get; set; }
        public bool geSale { get; set; }
        public bool geInElectronicPurse { get; set; }
        public Nullable<int> geConsecutiveElectronicPurse { get; set; }
        public bool geCancelElectronicPurse { get; set; }
        public bool geInPVPPromo { get; set; }
        public bool geCancelPVPPromo { get; set; }
        public bool geInOpera { get; set; }
        public bool geAsPromotionOpera { get; set; }
        public string geComments { get; set; }
        public string Package { get; set; }
    }
}
