//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public string gopy { get; set; }
        public string goPlaceID { get; set; }
        public System.DateTime goDateFrom { get; set; }
        public System.DateTime goDateTo { get; set; }
        public string gopd { get; set; }
        public decimal goGoal { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual PlaceType PlaceType { get; set; }
    }
}
