//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class GraphTotals
    {
        public int MaxGraphW { get; set; }
        public int MaxGraphM { get; set; }
        public Nullable<int> TotalW { get; set; }
        public Nullable<int> TotalM { get; set; }
    }
}
