//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class GraphProduction_Months
    {
        public Nullable<byte> Period { get; set; }
        public Nullable<int> Arrivals { get; set; }
        public Nullable<int> Availables { get; set; }
        public Nullable<decimal> AvailablesFactor { get; set; }
        public Nullable<int> Contacts { get; set; }
        public Nullable<decimal> ContactsFactor { get; set; }
        public Nullable<int> Books { get; set; }
        public Nullable<decimal> BooksFactor { get; set; }
        public Nullable<int> Shows { get; set; }
        public Nullable<decimal> ShowsFactor { get; set; }
        public Nullable<int> Sales { get; set; }
        public Nullable<decimal> ClosingFactor { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
    }
}
