//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class GuestPremanifestHost
    {
        public Nullable<byte> guShowSeq { get; set; }
        public int guID { get; set; }
        public string guls { get; set; }
        public string guloInvit { get; set; }
        public bool guQuinella { get; set; }
        public string guHReservID { get; set; }
        public string guOutInvitNum { get; set; }
        public Nullable<System.DateTime> guBookT { get; set; }
        public string guLastName1 { get; set; }
        public string guLastName2 { get; set; }
        public string guFirstName1 { get; set; }
        public string guFirstName2 { get; set; }
        public string guHotel { get; set; }
        public string guRoomNum { get; set; }
        public System.DateTime guCheckInD { get; set; }
        public System.DateTime guCheckOutD { get; set; }
        public string guco { get; set; }
        public string coN { get; set; }
        public string guag { get; set; }
        public string agN { get; set; }
        public decimal guDeposit { get; set; }
        public string cuN { get; set; }
        public string guPRInvit1 { get; set; }
        public string guMembershipNum { get; set; }
        public decimal guDepositReceived { get; set; }
        public Nullable<bool> refund { get; set; }
        public decimal guTaxiIn { get; set; }
        public bool guShow { get; set; }
        public bool guTour { get; set; }
        public bool guInOut { get; set; }
        public bool guWalkOut { get; set; }
        public bool guCTour { get; set; }
        public bool guSaveProgram { get; set; }
        public bool guWithQuinella { get; set; }
        public Nullable<System.DateTime> guTimeInT { get; set; }
        public Nullable<System.DateTime> guTimeOutT { get; set; }
        public bool guMealTicket { get; set; }
        public bool guSale { get; set; }
        public bool guGiftsReceived { get; set; }
        public string guWComments { get; set; }
        public decimal guPax { get; set; }
        public Nullable<bool> guResch { get; set; }
        public bool guBookCanc { get; set; }
    }
}
