//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest()
        {
            this.DepositsRefunds = new HashSet<DepositRefund>();
            this.GiftsReceipts = new HashSet<GiftsReceipt>();
            this.Groups = new HashSet<Group>();
            this.GuestsMovements = new HashSet<GuestMovement>();
            this.GuestsPromotions = new HashSet<GuestPromotion>();
            this.InvitsGifts = new HashSet<InvitationGift>();
            this.MealTickets = new HashSet<MealTicket>();
            this.PRNotes = new HashSet<PRNote>();
            this.Sales = new HashSet<Sale>();
            this.SalesLogs = new HashSet<SaleLog>();
            this.ShowsSalesmen = new HashSet<ShowSalesman>();
            this.Guests1 = new HashSet<Guest>();
            this.Guests = new HashSet<Guest>();
            this.GuestsGroups = new HashSet<GuestsGroup>();
        }
    
        public int guID { get; set; }
        public string guHReservID { get; set; }
        public string guls { get; set; }
        public string guMembershipNum { get; set; }
        public bool guOnGroup { get; set; }
        public string guHotel { get; set; }
        public string guRoomNum { get; set; }
        public System.DateTime guCheckInD { get; set; }
        public System.DateTime guCheckOutD { get; set; }
        public bool guCheckIn { get; set; }
        public string guLastName1 { get; set; }
        public string guFirstName1 { get; set; }
        public Nullable<byte> guAge1 { get; set; }
        public string gums1 { get; set; }
        public string guLastname2 { get; set; }
        public string guFirstName2 { get; set; }
        public Nullable<byte> guAge2 { get; set; }
        public string gums2 { get; set; }
        public decimal guPax { get; set; }
        public string guag { get; set; }
        public string guco { get; set; }
        public string gumk { get; set; }
        public string gula { get; set; }
        public bool guLW { get; set; }
        public bool guNW { get; set; }
        public bool guAvail { get; set; }
        public bool guInfo { get; set; }
        public bool guInvit { get; set; }
        public string guloInfo { get; set; }
        public string guloInvit { get; set; }
        public string guPRAssign { get; set; }
        public string guPRAvail { get; set; }
        public string guPRInfo { get; set; }
        public string guPRInvit1 { get; set; }
        public bool guSelfGen { get; set; }
        public string guPRInvit2 { get; set; }
        public string guPRInvit3 { get; set; }
        public string guPRCaptain1 { get; set; }
        public string guPRCaptain2 { get; set; }
        public string guPRCaptain3 { get; set; }
        public byte guum { get; set; }
        public Nullable<System.DateTime> guInfoD { get; set; }
        public string gumo { get; set; }
        public bool gumoA { get; set; }
        public string guComments { get; set; }
        public bool guQuinella { get; set; }
        public string guOutInvitNum { get; set; }
        public string guCity { get; set; }
        public string guState { get; set; }
        public Nullable<System.DateTime> guInvitD { get; set; }
        public Nullable<System.DateTime> guInvitT { get; set; }
        public bool guResch { get; set; }
        public Nullable<System.DateTime> guReschD { get; set; }
        public Nullable<System.DateTime> guReschT { get; set; }
        public Nullable<System.DateTime> guBookD { get; set; }
        public Nullable<System.DateTime> guBookT { get; set; }
        public Nullable<System.DateTime> guPickUpT { get; set; }
        public bool guDirect { get; set; }
        public bool guBookCanc { get; set; }
        public Nullable<System.DateTime> guShowD { get; set; }
        public string gusr { get; set; }
        public string guHotelB { get; set; }
        public decimal guDeposit { get; set; }
        public decimal guDepositTwisted { get; set; }
        public decimal guDepositReceived { get; set; }
        public string gucu { get; set; }
        public string guCCType { get; set; }
        public string guExtraInfo { get; set; }
        public Nullable<System.DateTime> guTimeInT { get; set; }
        public Nullable<System.DateTime> guTimeOutT { get; set; }
        public string guOccup1 { get; set; }
        public string guOccup2 { get; set; }
        public decimal guTaxiIn { get; set; }
        public decimal guTaxiOut { get; set; }
        public Nullable<int> guDepositgr { get; set; }
        public Nullable<int> guTaxiIngr { get; set; }
        public Nullable<int> guTaxiOutgr { get; set; }
        public bool guShow { get; set; }
        public Nullable<byte> guShowSeq { get; set; }
        public bool guQ { get; set; }
        public string guQType { get; set; }
        public bool guNQ { get; set; }
        public bool guCTour { get; set; }
        public bool guInOut { get; set; }
        public bool guWalkOut { get; set; }
        public bool guMealTicket { get; set; }
        public int guMealTicketQty { get; set; }
        public string guMealTicketFolios { get; set; }
        public bool guSale { get; set; }
        public bool guGiftsReceived { get; set; }
        public string guEntryHost { get; set; }
        public string guGiftsHost { get; set; }
        public string guExitHost { get; set; }
        public byte guLiner1Type { get; set; }
        public string guLiner1 { get; set; }
        public string guLiner2 { get; set; }
        public string guLinerCaptain1 { get; set; }
        public string guCloser1 { get; set; }
        public string guCloser2 { get; set; }
        public string guCloser3 { get; set; }
        public string guExit1 { get; set; }
        public string guExit2 { get; set; }
        public string guCloserCaptain1 { get; set; }
        public string guPodium { get; set; }
        public string guVLO { get; set; }
        public string guWComments { get; set; }
        public string guGComments { get; set; }
        public string guEComments { get; set; }
        public string guStatus { get; set; }
        public bool guInternetTransfer { get; set; }
        public string guO1 { get; set; }
        public string guO2 { get; set; }
        public string guO3 { get; set; }
        public string guO4 { get; set; }
        public string guO5 { get; set; }
        public string guO6 { get; set; }
        public bool guTwistedDeposit { get; set; }
        public Nullable<int> guInvitNum { get; set; }
        public string guTO { get; set; }
        public string guoc { get; set; }
        public bool guDepositRet { get; set; }
        public bool guTaxiInRet { get; set; }
        public bool guTaxiOutRet { get; set; }
        public Nullable<System.DateTime> guFirstBookD { get; set; }
        public string guHReservIDC { get; set; }
        public Nullable<int> guRef { get; set; }
        public Nullable<System.DateTime> guTimeCloserT { get; set; }
        public Nullable<System.DateTime> guTimeExitT { get; set; }
        public bool guTour { get; set; }
        public bool guShow2 { get; set; }
        public Nullable<System.DateTime> guShow2D { get; set; }
        public bool guQ2 { get; set; }
        public string guQType2 { get; set; }
        public bool guNQ2 { get; set; }
        public bool guCTour2 { get; set; }
        public bool guDirect2 { get; set; }
        public bool guQuinella2 { get; set; }
        public bool guTour2 { get; set; }
        public bool guInOut2 { get; set; }
        public bool guWalkOut2 { get; set; }
        public Nullable<System.DateTime> guTimeIn2T { get; set; }
        public Nullable<System.DateTime> guTimeCloser2T { get; set; }
        public Nullable<System.DateTime> guTimeExit2T { get; set; }
        public Nullable<System.DateTime> guTimeOut2T { get; set; }
        public string guFlight { get; set; }
        public string guGStatus { get; set; }
        public decimal guDepSale { get; set; }
        public string gulsOriginal { get; set; }
        public bool guAntesIO { get; set; }
        public Nullable<System.DateTime> guReschDT { get; set; }
        public string guDepositSaleNum { get; set; }
        public Nullable<System.DateTime> guDepositSaleD { get; set; }
        public int guRoomsQty { get; set; }
        public byte guChildren { get; set; }
        public string guChildrenAges { get; set; }
        public bool guQuinellaSplit { get; set; }
        public bool guOriginAvail { get; set; }
        public byte guDivResConsec { get; set; }
        public string guDivResLeadSource { get; set; }
        public string guDivResResNum { get; set; }
        public string guGuestRef { get; set; }
        public byte guShowsQty { get; set; }
        public bool guFamily { get; set; }
        public Nullable<System.DateTime> guBirthDate1 { get; set; }
        public Nullable<System.DateTime> guBirthDate2 { get; set; }
        public Nullable<System.DateTime> guBirthDate3 { get; set; }
        public Nullable<System.DateTime> guBirthDate4 { get; set; }
        public string guts { get; set; }
        public string guEmail1 { get; set; }
        public string guEmail2 { get; set; }
        public Nullable<int> guMainInvit { get; set; }
        public bool guOverflow { get; set; }
        public bool guIdentification { get; set; }
        public string guAccountGiftsCard { get; set; }
        public int guQtyGiftsCard { get; set; }
        public System.DateTime guCheckOutHotelD { get; set; }
        public bool guIncludedTour { get; set; }
        public bool guFollow { get; set; }
        public Nullable<System.DateTime> guFollowD { get; set; }
        public string guPRFollow { get; set; }
        public string guReservationType { get; set; }
        public string guHotelPrevious { get; set; }
        public string guFolioPrevious { get; set; }
        public bool guGroup { get; set; }
        public Nullable<int> gunb { get; set; }
        public Nullable<System.DateTime> guNoBookD { get; set; }
        public string guPRNoBook { get; set; }
        public bool guPRNote { get; set; }
        public decimal guCompany { get; set; }
        public bool guSaveProgram { get; set; }
        public bool guWithQuinella { get; set; }
        public string guIdProfileOpera { get; set; }
        public bool guAvailBySystem { get; set; }
        public string gurt { get; set; }
        public Nullable<int> gucl { get; set; }
        public string gupt { get; set; }
        public System.DateTime guCreationD { get; set; }
        public bool guInterval { get; set; }
        public Nullable<byte> guReimpresion { get; set; }
        public Nullable<byte> gurm { get; set; }
        public Nullable<bool> guPresentedInvitation { get; set; }
        public string guLastNameOriginal { get; set; }
        public string guFirstNameOriginal { get; set; }
        public Nullable<bool> guDespositRefund { get; set; }
        public Nullable<bool> guDepositsRefund { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Club Club { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositRefund> DepositsRefunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsReceipt> GiftsReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        public virtual GuestOpera GuestOpera { get; set; }
        public virtual NotBookingMotive NotBookingMotive { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Personnel Personnel1 { get; set; }
        public virtual Personnel Personnel2 { get; set; }
        public virtual Personnel Personnel3 { get; set; }
        public virtual Personnel Personnel4 { get; set; }
        public virtual Personnel Personnel5 { get; set; }
        public virtual Personnel Personnel6 { get; set; }
        public virtual Personnel Personnel7 { get; set; }
        public virtual Personnel Personnel8 { get; set; }
        public virtual Personnel Personnel9 { get; set; }
        public virtual Personnel Personnel10 { get; set; }
        public virtual Personnel Personnel11 { get; set; }
        public virtual Personnel Personnel12 { get; set; }
        public virtual Personnel Personnel13 { get; set; }
        public virtual Personnel Personnel14 { get; set; }
        public virtual Personnel Personnel15 { get; set; }
        public virtual Personnel Personnel16 { get; set; }
        public virtual Personnel Personnel17 { get; set; }
        public virtual Personnel Personnel18 { get; set; }
        public virtual Personnel Personnel19 { get; set; }
        public virtual Personnel Personnel20 { get; set; }
        public virtual Personnel Personnel21 { get; set; }
        public virtual Personnel Personnel22 { get; set; }
        public virtual Personnel Personnel23 { get; set; }
        public virtual Personnel Personnel24 { get; set; }
        public virtual ReimpresionMotive ReimpresionMotive { get; set; }
        public virtual RoomType RoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestMovement> GuestsMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestPromotion> GuestsPromotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvitationGift> InvitsGifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealTicket> MealTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRNote> PRNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleLog> SalesLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowSalesman> ShowsSalesmen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestsGroup> GuestsGroups { get; set; }
    }
}
