//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class GuestLogData
    {
        public string glChangedBy { get; set; }
        public string ChangedByN { get; set; }
        public System.DateTime glID { get; set; }
        public string glsr { get; set; }
        public string glHReservID { get; set; }
        public string glLastName1 { get; set; }
        public string glFirstName1 { get; set; }
        public string glLastName2 { get; set; }
        public string glFirstName2 { get; set; }
        public bool glAvailBySystem { get; set; }
        public bool glOriginAvail { get; set; }
        public bool glAvail { get; set; }
        public string umN { get; set; }
        public string glPRAvail { get; set; }
        public string PRAvailN { get; set; }
        public Nullable<System.DateTime> glInfoD { get; set; }
        public string glPRInfo { get; set; }
        public string PRInfoN { get; set; }
        public Nullable<System.DateTime> glFollowD { get; set; }
        public string glPRFollow { get; set; }
        public string PRFollowN { get; set; }
        public Nullable<System.DateTime> glBookD { get; set; }
        public Nullable<System.DateTime> glBookT { get; set; }
        public Nullable<System.DateTime> glReschD { get; set; }
        public Nullable<System.DateTime> glReschT { get; set; }
        public string glPRInvit1 { get; set; }
        public string PRInvit1N { get; set; }
        public string glPRInvit2 { get; set; }
        public string PRInvit2N { get; set; }
        public bool glBookCanc { get; set; }
        public string glLiner1 { get; set; }
        public string Liner1N { get; set; }
        public string glLiner2 { get; set; }
        public string Liner2N { get; set; }
        public string glCloser1 { get; set; }
        public string Closer1N { get; set; }
        public string glCloser2 { get; set; }
        public string Closer2N { get; set; }
        public string glCloser3 { get; set; }
        public string Closer3N { get; set; }
        public string glExit1 { get; set; }
        public string Exit1N { get; set; }
        public string glExit2 { get; set; }
        public string Exit2N { get; set; }
        public string glPodium { get; set; }
        public string PodiumN { get; set; }
        public string glVLO { get; set; }
        public string VLON { get; set; }
        public bool glShow { get; set; }
        public Nullable<System.DateTime> glShowD { get; set; }
        public bool glQ { get; set; }
        public bool glInOut { get; set; }
        public bool glWalkOut { get; set; }
        public bool glCTour { get; set; }
        public Nullable<byte> glReimpresion { get; set; }
        public string rmN { get; set; }
    }
}
