//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestStatusType
    {
        public string gsID { get; set; }
        public string gsN { get; set; }
        public bool gsA { get; set; }
        public byte gsAgeStart { get; set; }
        public byte gsAgeEnd { get; set; }
        public decimal gsMaxAuthGifts { get; set; }
        public Nullable<int> gsMaxQtyTours { get; set; }
        public Nullable<bool> gsAllowTourDisc { get; set; }
    }
}
