//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class GuestShort
    {
        public int guID { get; set; }
        public string guLastName1 { get; set; }
        public string guFirstName1 { get; set; }
        public string Name { get; set; }
        public string gulsOriginal { get; set; }
        public string guls { get; set; }
        public string lsPropertyOpera { get; set; }
        public Nullable<bool> lsUseSistur { get; set; }
        public string guloInvit { get; set; }
        public string lspg { get; set; }
        public string pgN { get; set; }
        public string gusr { get; set; }
        public string srPropertyOpera { get; set; }
        public Nullable<bool> srUseSistur { get; set; }
        public string guHReservID { get; set; }
        public string guRoomNum { get; set; }
        public System.DateTime guCheckInD { get; set; }
        public System.DateTime guCheckOutD { get; set; }
        public string guag { get; set; }
        public string agN { get; set; }
        public string guAccountGiftsCard { get; set; }
        public int guQtyGiftsCard { get; set; }
        public bool guSelfGen { get; set; }
        public string guPRInvit1 { get; set; }
        public string guPRInvit2 { get; set; }
        public string guPRInvit3 { get; set; }
        public string guPRAssign { get; set; }
        public byte guLiner1Type { get; set; }
        public string guLiner1 { get; set; }
        public string guLiner2 { get; set; }
        public string guCloser1 { get; set; }
        public string guCloser2 { get; set; }
        public string guCloser3 { get; set; }
        public string guExit1 { get; set; }
        public string guExit2 { get; set; }
        public string guPodium { get; set; }
        public string guVLO { get; set; }
    }
}
