//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class GuestMovements
    {
        public string gmpe { get; set; }
        public string peN { get; set; }
        public System.DateTime gmDT { get; set; }
        public string gnN { get; set; }
        public string gmcp { get; set; }
        public string cpN { get; set; }
        public string gmIpAddress { get; set; }
    }
}
