//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class GuestPremanifest
    {
        public string guStatus { get; set; }
        public int guID { get; set; }
        public string guIdProfileOpera { get; set; }
        public bool guCheckIn { get; set; }
        public string guRoomNum { get; set; }
        public string guLastName1 { get; set; }
        public string guFirstName1 { get; set; }
        public System.DateTime guCheckInD { get; set; }
        public System.DateTime guCheckOutD { get; set; }
        public string guco { get; set; }
        public string coN { get; set; }
        public string guag { get; set; }
        public string agN { get; set; }
        public Nullable<int> agcl { get; set; }
        public decimal guPax { get; set; }
        public string guO2 { get; set; }
        public string guCCType { get; set; }
        public string guPRAssign { get; set; }
        public bool guAvail { get; set; }
        public bool guInfo { get; set; }
        public string guPRInfo { get; set; }
        public bool guFollow { get; set; }
        public Nullable<System.DateTime> guFollowD { get; set; }
        public string guPRFollow { get; set; }
        public bool guInvit { get; set; }
        public Nullable<System.DateTime> guInvitD { get; set; }
        public Nullable<System.DateTime> guInvitT { get; set; }
        public Nullable<bool> guResch { get; set; }
        public Nullable<System.DateTime> guBookD { get; set; }
        public Nullable<System.DateTime> guBookT { get; set; }
        public string guPRInvit1 { get; set; }
        public Nullable<int> gunb { get; set; }
        public Nullable<System.DateTime> guNoBookD { get; set; }
        public string guPRNoBook { get; set; }
        public bool guQuinella { get; set; }
        public Nullable<int> gagu { get; set; }
        public bool guGroup { get; set; }
        public string Equity { get; set; }
        public Nullable<int> gucl { get; set; }
        public string clN { get; set; }
        public decimal guCompany { get; set; }
        public string guMembershipNum { get; set; }
        public string mtN { get; set; }
        public bool guShow { get; set; }
        public bool guTour { get; set; }
        public bool guBookCanc { get; set; }
        public bool guSale { get; set; }
        public bool guLW { get; set; }
        public bool guPRNote { get; set; }
        public string Notes { get; set; }
        public string guComments { get; set; }
    }
}
