//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvitationGift
    {
        public int iggu { get; set; }
        public string iggi { get; set; }
        public string igct { get; set; }
        public int igQty { get; set; }
        public int igAdults { get; set; }
        public int igMinors { get; set; }
        public Nullable<int> iggr { get; set; }
        public string igFolios { get; set; }
        public decimal igPriceA { get; set; }
        public decimal igPriceM { get; set; }
        public string igComments { get; set; }
        public int igExtraAdults { get; set; }
        public decimal igPriceAdult { get; set; }
        public decimal igPriceMinor { get; set; }
        public decimal igPriceExtraAdult { get; set; }
    
        public virtual ChargeTo ChargeTo { internal get; set; }
        public virtual Gift Gift { internal get; set; }
        public virtual GiftsReceipt GiftsReceipt { internal get; set; }
        public virtual Guest Guest { internal get; set; }
    }
}
