//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeadSource()
        {
            this.lsEfficiencyTh = 1200m;
            this.lsShowFactorTh = 0.6m;
            this.lsBookFactorTh = 55m;
            this.lsShowsTh = 10;
            this.lsProcesar = true;
            this.lsCECOID = "";
            this.GiftsReceipts = new HashSet<GiftsReceipt>();
            this.InvitationsTexts = new HashSet<InvitationText>();
            this.MailOuts = new HashSet<MailOut>();
            this.MailOutTexts = new HashSet<MailOutText>();
            this.RoomCharges = new HashSet<RoomCharge>();
            this.Sales = new HashSet<Sale>();
            this.SalesLogs = new HashSet<SaleLog>();
            this.ScoreRulesByLeadSourceDetails = new HashSet<ScoreRuleByLeadSourceDetail>();
            this.Agencies = new HashSet<Agency>();
            this.Notices = new HashSet<Notice>();
        }
    
        public string lsID { get; set; }
        public string lsN { get; set; }
        public string lspg { get; set; }
        public int lsRooms { get; set; }
        public string lssr { get; set; }
        public string lsar { get; set; }
        public string lsrg { get; set; }
        public short lsHoursDif { get; set; }
        public bool lsPayInOut { get; set; }
        public bool lsPayWalkOut { get; set; }
        public bool lsRunTrans { get; set; }
        public System.DateTime lsTransDT { get; set; }
        public System.DateTime lsTransBridgeDT { get; set; }
        public decimal lsEfficiencyTh { get; set; }
        public decimal lsShowFactorTh { get; set; }
        public decimal lsBookFactorTh { get; set; }
        public int lsShowsTh { get; set; }
        public bool lsDBMaint { get; set; }
        public bool lsA { get; set; }
        public Nullable<System.DateTime> lsStartD { get; set; }
        public string lsFTPServer { get; set; }
        public string lsFTPPath { get; set; }
        public string lsFTPFile { get; set; }
        public string lsFTPUserN { get; set; }
        public string lsFTPPwd { get; set; }
        public string lsNTDrive { get; set; }
        public string lsNTPath { get; set; }
        public string lsIHEStdFile { get; set; }
        public string lsCommand1 { get; set; }
        public bool lsProcesar { get; set; }
        public decimal lsMaxAuthGifts { get; set; }
        public string lsHotel { get; set; }
        public string lsso { get; set; }
        public string lsZone { get; set; }
        public string lszn { get; set; }
        public string lsBoss { get; set; }
        public bool lsUseOpera { get; set; }
        public bool lsRegen { get; set; }
        public bool lsAnimation { get; set; }
        public string lsho { get; set; }
        public bool lsUseSistur { get; set; }
        public string lsPropertyOpera { get; set; }
        public string lsCECOID { get; set; }
    
        public virtual Area Area { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsReceipt> GiftsReceipts { internal get; set; }
        public virtual Hotel Hotel { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvitationText> InvitationsTexts { internal get; set; }
        public virtual Personnel Personnel { internal get; set; }
        public virtual Program Program { internal get; set; }
        public virtual Region Region { internal get; set; }
        public virtual SegmentByLeadSource SegmentByLeadSource { internal get; set; }
        public virtual Zone Zone { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailOut> MailOuts { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailOutText> MailOutTexts { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomCharge> RoomCharges { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleLog> SalesLogs { internal get; set; }
        public virtual ScoreRuleByLeadSource ScoreRuleByLeadSource { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreRuleByLeadSourceDetail> ScoreRulesByLeadSourceDetails { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agency> Agencies { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notice> Notices { internal get; set; }
    }
}
