//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailOutText
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MailOutText()
        {
            this.mtla = "EN";
            this.mtA = true;
        }
    
        public string mtls { get; set; }
        public string mtmoCode { get; set; }
        public string mtla { get; set; }
        public string mtRTF { get; set; }
        public bool mtA { get; set; }
        public System.DateTime mtU { get; set; }
    
        public virtual Language Language { internal get; set; }
        public virtual LeadSource LeadSource { internal get; set; }
    }
}
