//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealTicket
    {
        public int meID { get; set; }
        public System.DateTime meD { get; set; }
        public int megu { get; set; }
        public int meQty { get; set; }
        public string meType { get; set; }
        public int meAdults { get; set; }
        public int meMinors { get; set; }
        public string meFolios { get; set; }
        public decimal meTAdults { get; set; }
        public decimal meTMinors { get; set; }
        public string meComments { get; set; }
        public string mesr { get; set; }
        public bool meCanc { get; set; }
        public int mera { get; set; }
        public string mepe { get; set; }
        public bool mePrinted { get; set; }
        public string meag { get; set; }
        public string merep { get; set; }
        public string meAuthorizedBy { get; set; }
    
        public virtual Agency Agency { internal get; set; }
        public virtual Guest Guest { internal get; set; }
        public virtual MealTicketType MealTicketType { internal get; set; }
        public virtual Personnel Personnel { internal get; set; }
        public virtual RateType RateType { internal get; set; }
        public virtual SalesRoom SalesRoom { internal get; set; }
    }
}
