//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class MealTicketData
    {
        public string meType { get; set; }
        public string myN { get; set; }
        public int megu { get; set; }
        public string Name { get; set; }
        public System.DateTime meD { get; set; }
        public string mepe { get; set; }
        public string Authorized { get; set; }
        public int meFolio { get; set; }
        public string gula { get; set; }
        public int meAdults { get; set; }
        public int meMinors { get; set; }
        public int guID { get; set; }
        public string SalesRoomID { get; set; }
        public string SalesRoomName { get; set; }
        public string raN { get; set; }
        public string REFERENCE { get; set; }
        public string REFERENCENAME { get; set; }
    }
}
