//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class MembershipTypeShort
    {
        public string mtID { get; set; }
        public string mtN { get; set; }
        public Nullable<byte> mtLevel { get; set; }
    }
}
