//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSchema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentSchema()
        {
            this.pasA = true;
        }
    
        public int pasID { get; set; }
        public string pasN { get; set; }
        public int pasCoupleFrom { get; set; }
        public int pasCoupleTo { get; set; }
        public decimal pasShowFactor { get; set; }
        public bool pasA { get; set; }
    }
}
