//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSchema
    {
        public int pasID { get; set; }
        public string pasN { get; set; }
        public Nullable<int> pasCoupleFrom { get; set; }
        public Nullable<int> pasCoupleTo { get; set; }
        public Nullable<decimal> pasShowFactor { get; set; }
        public Nullable<bool> pasA { get; set; }
    }
}
