//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class PersonnelDayOff
    {
        public string dope { get; set; }
        public string peN { get; set; }
        public string doList { get; set; }
        public string poN { get; set; }
        public Nullable<bool> doMonday { get; set; }
        public Nullable<bool> doTuesday { get; set; }
        public Nullable<bool> doWednesday { get; set; }
        public Nullable<bool> doThursday { get; set; }
        public Nullable<bool> doFriday { get; set; }
        public Nullable<bool> doSaturday { get; set; }
        public Nullable<bool> doSunday { get; set; }
    }
}
