//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonnelLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonnelLog()
        {
            this.LeadSources = new HashSet<LeadSource>();
            this.Roles = new HashSet<Role>();
            this.SalesRooms = new HashSet<SalesRoom>();
        }
    
        public int plgID { get; set; }
        public string plgpe { get; set; }
        public System.DateTime plgDT { get; set; }
        public string plgChangedBy { get; set; }
        public string plgde { get; set; }
        public string plgpo { get; set; }
        public string plgsr { get; set; }
        public string plglo { get; set; }
    
        public virtual Dept Dept { get; set; }
        public virtual Location Location { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Personnel Personnel1 { get; set; }
        public virtual Post Post { get; set; }
        public virtual SalesRoom SalesRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadSource> LeadSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesRoom> SalesRooms { get; set; }
    }
}
