//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportText
    {
        public string reReport { get; set; }
        public string reTextId { get; set; }
        public string rela { get; set; }
        public int reO { get; set; }
        public bool reIsSection { get; set; }
        public string reText { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
