//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptAssignmentByPR
    {
        public System.DateTime guCheckInD { get; set; }
        public System.DateTime guCheckOutD { get; set; }
        public string guRoomNum { get; set; }
        public string guLastName1 { get; set; }
        public string guFirstName1 { get; set; }
        public string guag { get; set; }
        public string agN { get; set; }
        public string guMemberShipNum { get; set; }
        public string guO1 { get; set; }
        public string guComments { get; set; }
        public string guPRAssign { get; set; }
        public string peN { get; set; }
        public decimal guPax { get; set; }
    }
}
