//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptAssignmentArrivals
    {
        public int guID { get; set; }
        public System.DateTime guCheckInD { get; set; }
        public bool guCheckIn { get; set; }
        public string guRoomNum { get; set; }
        public string guLastName1 { get; set; }
        public string guFirstName1 { get; set; }
        public string guPRAssign { get; set; }
        public string peN { get; set; }
        public string guag { get; set; }
        public string agN { get; set; }
        public string guMemberShipNum { get; set; }
        public string Gross { get; set; }
        public string PR { get; set; }
        public string Liner { get; set; }
        public string Closer { get; set; }
    }
}
