//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptCxCPayments
    {
        public int grID { get; set; }
        public System.DateTime grD { get; set; }
        public string grls { get; set; }
        public string grpe { get; set; }
        public string peN { get; set; }
        public decimal AmountToPayUSD { get; set; }
        public decimal AmountToPayMXN { get; set; }
        public decimal AmountPaidUSD { get; set; }
        public decimal AmountPaidMXN { get; set; }
        public decimal BalanceUSD { get; set; }
        public decimal BalanceMXN { get; set; }
        public Nullable<int> grgu { get; set; }
        public string guHReservID { get; set; }
        public string guOutInvitNum { get; set; }
        public System.DateTime cxD { get; set; }
        public string cxReceivedBy { get; set; }
        public string ReceivedByName { get; set; }
        public decimal AmountUSD { get; set; }
        public decimal AmountMXN { get; set; }
    }
}
