//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptCxC
    {
        public string grGroup { get; set; }
        public string grpe { get; set; }
        public string peN { get; set; }
        public int grID { get; set; }
        public string grNum { get; set; }
        public System.DateTime grD { get; set; }
        public Nullable<int> grgu { get; set; }
        public string grGuest { get; set; }
        public int geQty { get; set; }
        public string giN { get; set; }
        public int geAdults { get; set; }
        public int geMinors { get; set; }
        public string geFolios { get; set; }
        public decimal TotalGift { get; set; }
        public decimal grCxCGifts { get; set; }
        public decimal grCxCAdj { get; set; }
        public decimal grCxCPRDeposit { get; set; }
        public string grcuCxCPRDeposit { get; set; }
        public decimal ExchRateDeposit { get; set; }
        public Nullable<decimal> CxCDepositUS { get; set; }
        public Nullable<decimal> CxCDepositMN { get; set; }
        public decimal grCxCTaxiOut { get; set; }
        public string grcuCxCTaxiOut { get; set; }
        public decimal ExchRateTaxiOut { get; set; }
        public Nullable<decimal> CxCTaxiOutUS { get; set; }
        public Nullable<decimal> CxCTaxiOutMN { get; set; }
        public Nullable<decimal> TotalCxC { get; set; }
        public Nullable<decimal> CxCPaidUS { get; set; }
        public Nullable<decimal> CxCPaidMN { get; set; }
        public decimal ExchRateSalesRoom { get; set; }
        public string grCxCComments { get; set; }
        public string grComments { get; set; }
    }
}
