//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptCostByPR
    {
        public string PR { get; set; }
        public string PRN { get; set; }
        public Nullable<decimal> Shows { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> AverageCost { get; set; }
    }
}
