//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptCxCGifts
    {
        public int grID { get; set; }
        public string grNum { get; set; }
        public string grpe { get; set; }
        public string peN { get; set; }
        public string grlo { get; set; }
        public string grHost { get; set; }
        public string HostN { get; set; }
        public Nullable<int> grgu { get; set; }
        public string grGuest { get; set; }
        public string Gift { get; set; }
        public int Quantity { get; set; }
        public int Adults { get; set; }
        public int Minors { get; set; }
        public string Folios { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime grD { get; set; }
        public decimal CostUS { get; set; }
        public decimal exExchRate { get; set; }
        public Nullable<decimal> CostMX { get; set; }
        public string grMemberNum { get; set; }
        public string grCxCComments { get; set; }
    }
}
