//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptCxCExcel
    {
        public string grpe { get; set; }
        public System.DateTime grD { get; set; }
        public string grNum { get; set; }
        public string grsr { get; set; }
        public string peN { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> CxC { get; set; }
        public Nullable<decimal> exExchRate { get; set; }
        public Nullable<decimal> CxCP { get; set; }
        public Nullable<decimal> TotalCxC { get; set; }
        public Nullable<decimal> ToPayUS { get; set; }
        public Nullable<decimal> ToPayMN { get; set; }
    }
}
