//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptConcentrateDailySales
    {
        public string SalesRoom { get; set; }
        public Nullable<int> UPS { get; set; }
        public Nullable<int> Sales { get; set; }
        public Nullable<decimal> SalesAmountOPP { get; set; }
        public Nullable<decimal> SalesAmountFall { get; set; }
        public Nullable<decimal> SalesAmountCancel { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<decimal> DownPact { get; set; }
        public Nullable<decimal> DownColl { get; set; }
    }
}
