//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptDepositsPaymentByPR_Deposit
    {
        public string Category { get; set; }
        public string pcN { get; set; }
        public string PaymentSchema { get; set; }
        public Nullable<decimal> PaymentSchemaFactor { get; set; }
        public string PR { get; set; }
        public string PRN { get; set; }
        public int guID { get; set; }
        public string guName { get; set; }
        public Nullable<byte> guAge1 { get; set; }
        public Nullable<System.DateTime> guBookD { get; set; }
        public Nullable<System.DateTime> guShowD { get; set; }
        public string guOutInvitNum { get; set; }
        public string guHotel { get; set; }
        public string guls { get; set; }
        public string gusr { get; set; }
        public string bdpt { get; set; }
        public string bdcu { get; set; }
        public decimal bdAmount { get; set; }
        public decimal bdReceived { get; set; }
        public Nullable<decimal> ToPay { get; set; }
    }
}
