//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptDepositsPaymentByPR_Deposit
    {
        public string PR { get; set; }
        public int guID { get; set; }
        public string guName { get; set; }
        public Nullable<byte> guAge1 { get; set; }
        public Nullable<System.DateTime> guBookD { get; set; }
        public Nullable<System.DateTime> guShowD { get; set; }
        public string guOutInvitNum { get; set; }
        public string guHotel { get; set; }
        public string guls { get; set; }
        public string gusr { get; set; }
        public string bdpt { get; set; }
        public string bdcu { get; set; }
        public string bdpc { get; set; }
        public string tpshow { get; set; }
        public Nullable<decimal> bdAmount { get; set; }
        public Nullable<decimal> bdReceived { get; set; }
        public Nullable<decimal> topay { get; set; }
    }
}
