//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptDepositsBurnedByResort
    {
        public int grID { get; set; }
        public string grNum { get; set; }
        public System.DateTime grD { get; set; }
        public Nullable<int> grgu { get; set; }
        public string grGuest { get; set; }
        public string grHotel { get; set; }
        public string guHotelB { get; set; }
        public string grlo { get; set; }
        public string grsr { get; set; }
        public string grpe { get; set; }
        public string peN { get; set; }
        public string grcu { get; set; }
        public string grpt { get; set; }
        public string grHost { get; set; }
        public decimal grDepositTwisted { get; set; }
    }
}
