//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptFoliosCXC
    {
        public Nullable<int> bdFolioCXC { get; set; }
        public string PR { get; set; }
        public string PRN { get; set; }
        public string guOutInvitNum { get; set; }
        public string lsN { get; set; }
        public string guLastName1 { get; set; }
        public string guFirstName1 { get; set; }
        public Nullable<System.DateTime> guBookD { get; set; }
        public string bdUserCXC { get; set; }
        public string peN { get; set; }
        public Nullable<System.DateTime> bdEntryDCXC { get; set; }
        public string guStatus { get; set; }
        public bool guShow { get; set; }
        public string EsShow { get; set; }
        public Nullable<decimal> GrossBooks { get; set; }
        public Nullable<decimal> GrossShows { get; set; }
        public Nullable<decimal> ShowsFactor { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Books { get; set; }
        public Nullable<decimal> InOuts { get; set; }
        public Nullable<decimal> Shows { get; set; }
        public Nullable<decimal> CxC { get; set; }
        public string PaymentSchema { get; set; }
        public Nullable<decimal> PaymentSchemaFactor { get; set; }
    }
}
