//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptFTMInOutHouse
    {
        public string Liner { get; set; }
        public string peN { get; set; }
        public Nullable<decimal> OOP { get; set; }
        public Nullable<decimal> OFSalesAmount { get; set; }
        public Nullable<decimal> OFShows { get; set; }
        public Nullable<decimal> OFSales { get; set; }
        public Nullable<decimal> OFExit { get; set; }
        public Nullable<decimal> OFTotal { get; set; }
        public Nullable<decimal> RSalesAmount { get; set; }
        public Nullable<decimal> RShows { get; set; }
        public Nullable<decimal> OFSales1 { get; set; }
        public Nullable<decimal> RExit { get; set; }
        public Nullable<decimal> RTotal { get; set; }
        public Nullable<decimal> NSalesAmount { get; set; }
        public Nullable<decimal> NShows { get; set; }
        public Nullable<decimal> NSales { get; set; }
        public Nullable<decimal> NExit { get; set; }
        public Nullable<decimal> NTotal { get; set; }
        public Nullable<decimal> TSalesAmount { get; set; }
        public Nullable<decimal> TShows { get; set; }
        public Nullable<decimal> TSales { get; set; }
        public Nullable<decimal> TExit { get; set; }
        public Nullable<decimal> NTotal1 { get; set; }
    }
}
