//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptFoliosCxCByPR
    {
        public string lsID { get; set; }
        public string lsN { get; set; }
        public Nullable<int> guFrom { get; set; }
        public Nullable<int> guTo { get; set; }
        public string guPRInvit1 { get; set; }
        public string peN { get; set; }
        public string guLastName1 { get; set; }
        public string guFirstName1 { get; set; }
        public Nullable<System.DateTime> guBookD { get; set; }
        public string guStatus { get; set; }
    }
}
