//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGiftsReceipt_Gifts
    {
        public int geQty { get; set; }
        public string gegi { get; set; }
        public string giN { get; set; }
        public int geAdults { get; set; }
        public int geMinors { get; set; }
        public string geFolios { get; set; }
        public string geComments { get; set; }
        public string gipr { get; set; }
    }
}
