//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGiftsReceivedBySR
    {
        public string SalesRoom { get; set; }
        public string Gift { get; set; }
        public string GiftN { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Couples { get; set; }
        public Nullable<decimal> Adults { get; set; }
        public Nullable<decimal> Minors { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
