//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGuestRegistration_Gifts
    {
        public Nullable<int> guID { get; set; }
        public string FullName { get; set; }
        public int igQty { get; set; }
        public string giN { get; set; }
        public int igAdults { get; set; }
        public int igMinors { get; set; }
        public string igComments { get; set; }
        public int OrderInvit { get; set; }
    }
}
