//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGuestRegistration_Deposits
    {
        public decimal bdAmount { get; set; }
        public decimal bdReceived { get; set; }
        public string cuN { get; set; }
    }
}
