//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGiftsUsedBySistur
    {
        public string srN { get; set; }
        public string pgN { get; set; }
        public string lsN { get; set; }
        public int grID { get; set; }
        public System.DateTime grD { get; set; }
        public bool grCancel { get; set; }
        public Nullable<System.DateTime> grCancelD { get; set; }
        public bool grExchange { get; set; }
        public Nullable<int> guID { get; set; }
        public string guHReservID { get; set; }
        public string guOutInvitNum { get; set; }
        public string guLastName1 { get; set; }
        public string guFirstName1 { get; set; }
        public int geQty { get; set; }
        public Nullable<int> giQty { get; set; }
        public string giID { get; set; }
        public string giN { get; set; }
        public string Promotion { get; set; }
        public Nullable<int> Granted { get; set; }
        public bool geCancelPVPPromo { get; set; }
        public Nullable<int> gspUsed { get; set; }
        public Nullable<int> gspCoupon { get; set; }
        public Nullable<System.DateTime> gspD { get; set; }
        public Nullable<decimal> gspPax { get; set; }
        public Nullable<decimal> gspAmount { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int Difference { get; set; }
        public string Cecos { get; set; }
        public Nullable<decimal> sisturCost { get; set; }
    }
}
