//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGuestCeco
    {
        public string soccecoid { get; set; }
        public int guID { get; set; }
        public Nullable<System.DateTime> guBookD { get; set; }
        public string srN { get; set; }
        public string acn { get; set; }
        public string ceco { get; set; }
        public string mksN { get; set; }
    }
}
