//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGifts
    {
        public string giID { get; set; }
        public string giN { get; set; }
        public string giShortN { get; set; }
        public int giO { get; set; }
        public decimal giPrice1 { get; set; }
        public decimal giPrice2 { get; set; }
        public decimal giPrice3 { get; set; }
        public decimal giPrice4 { get; set; }
        public bool giPack { get; set; }
        public string gcN { get; set; }
        public bool giInven { get; set; }
        public bool giWFolio { get; set; }
        public bool giWPax { get; set; }
        public bool giA { get; set; }
    }
}
