//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGiftsManifestCancel
    {
        public Nullable<int> grgu { get; set; }
        public string grGuest { get; set; }
        public string grsr { get; set; }
        public string grlo { get; set; }
        public string grHost { get; set; }
        public string peN { get; set; }
        public int grID { get; set; }
        public System.DateTime grD { get; set; }
        public decimal grDeposit { get; set; }
        public decimal grDepositTwisted { get; set; }
        public string grcu { get; set; }
        public string grpt { get; set; }
        public decimal grTaxiOut { get; set; }
        public string gegi { get; set; }
        public Nullable<int> geQty { get; set; }
        public string geFolios { get; set; }
        public decimal gePriceA { get; set; }
        public decimal gePriceM { get; set; }
        public string grComments { get; set; }
    }
}
