//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGuestRegistration
    {
        public int guID { get; set; }
        public string guState { get; set; }
        public string guco { get; set; }
        public string coN { get; set; }
        public string guHotel { get; set; }
        public string guRoomNum { get; set; }
        public string loN { get; set; }
        public string guag { get; set; }
        public string agN { get; set; }
        public System.DateTime guCheckInD { get; set; }
        public System.DateTime guCheckOutD { get; set; }
        public decimal guDepositTwisted { get; set; }
        public string cuN { get; set; }
        public string guHotelB { get; set; }
        public string guOutInvitNum { get; set; }
        public decimal guPax { get; set; }
        public byte guChildren { get; set; }
        public string guChildrenAges { get; set; }
        public Nullable<System.DateTime> guShowD { get; set; }
        public Nullable<System.DateTime> guTimeInT { get; set; }
        public decimal guTaxiIn { get; set; }
        public bool guDirect { get; set; }
        public bool guInOut { get; set; }
        public bool guWalkOut { get; set; }
        public bool guIdentification { get; set; }
        public string EntryHostN { get; set; }
        public string gula { get; set; }
        public bool guQuinella { get; set; }
        public Nullable<byte> guReimpresion { get; set; }
        public string rmN { get; set; }
        public string Area { get; set; }
    }
}
