//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGiftsManifestCancel_Gifts
    {
        public string giID { get; set; }
        public string giN { get; set; }
        public Nullable<bool> giWFolio { get; set; }
        public string gigc { get; set; }
    }
}
