//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGiftsCertificates
    {
        public string GiftID { get; set; }
        public string GiftN { get; set; }
        public int Receipt { get; set; }
        public string Status { get; set; }
        public string Folios { get; set; }
        public System.DateTime Date { get; set; }
        public string Host { get; set; }
        public string Guest { get; set; }
        public string Location { get; set; }
        public Nullable<int> Adults { get; set; }
        public Nullable<int> Minors { get; set; }
        public Nullable<int> ExtraAdults { get; set; }
        public string Pax { get; set; }
        public Nullable<decimal> CxC { get; set; }
        public string PaymentType { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Refund { get; set; }
        public string Comments { get; set; }
    }
}
