//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptGiftsSale_Payment
    {
        public int Receipt { get; set; }
        public string Source { get; set; }
        public string Currency { get; set; }
        public string PaymentType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal ExchangeRate { get; set; }
        public Nullable<decimal> AmountUS { get; set; }
        public string User { get; set; }
        public string UserN { get; set; }
    }
}
