//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptInOut
    {
        public string SalesRoom { get; set; }
        public string Location { get; set; }
        public int GUID { get; set; }
        public string Hotel { get; set; }
        public string Room { get; set; }
        public decimal Pax { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Agency { get; set; }
        public string AgencyN { get; set; }
        public string Country { get; set; }
        public string CountryN { get; set; }
        public Nullable<System.DateTime> ShowDate { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public int Direct { get; set; }
        public bool Tour { get; set; }
        public bool InOut { get; set; }
        public bool WalkOut { get; set; }
        public bool CourtesyTour { get; set; }
        public bool SaveProgram { get; set; }
        public string PR1 { get; set; }
        public string PR1N { get; set; }
        public string PR2 { get; set; }
        public string PR2N { get; set; }
        public string PR3 { get; set; }
        public string PR3N { get; set; }
        public string Host { get; set; }
        public string Comments { get; set; }
    }
}
