//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptLoginLog
    {
        public System.DateTime Date_Time { get; set; }
        public string Location { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string PC { get; set; }
    }
}
