//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptMemberships
    {
        public int saID { get; set; }
        public System.DateTime saD { get; set; }
        public Nullable<System.DateTime> saProcD { get; set; }
        public Nullable<System.DateTime> saCancelD { get; set; }
        public string salo { get; set; }
        public string sasr { get; set; }
        public string saMembershipNum { get; set; }
        public string samt { get; set; }
        public string sast { get; set; }
        public string saLastName1 { get; set; }
        public string saFirstName1 { get; set; }
        public string saLastName2 { get; set; }
        public string saFirstName2 { get; set; }
        public decimal ProcAmount { get; set; }
        public decimal OOPAmount { get; set; }
        public decimal CancAmount { get; set; }
        public decimal PendAmount { get; set; }
        public string saPR1 { get; set; }
        public string saPR2 { get; set; }
        public string saPR3 { get; set; }
        public string saLiner1 { get; set; }
        public string saLiner2 { get; set; }
        public string saCloser1 { get; set; }
        public string saCloser2 { get; set; }
        public string saCloser3 { get; set; }
        public string saExit1 { get; set; }
        public string saExit2 { get; set; }
        public string saVLO { get; set; }
        public string saPodium { get; set; }
        public Nullable<int> sagu { get; set; }
        public string saComments { get; set; }
        public Nullable<decimal> TotalProcAmount { get; set; }
    }
}
