//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptManifestByLSRange_Bookings
    {
        public string guloInvit { get; set; }
        public string LocationN { get; set; }
        public string guBookT { get; set; }
        public Nullable<int> Bookings { get; set; }
    }
}
