//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptMembershipsByAgencyMarket
    {
        public string mkN { get; set; }
        public string agN { get; set; }
        public int saID { get; set; }
        public Nullable<System.DateTime> saProcD { get; set; }
        public string lsN { get; set; }
        public string srN { get; set; }
        public string saMembershipNum { get; set; }
        public string mtN { get; set; }
        public string sast { get; set; }
        public string saLastName1 { get; set; }
        public string saFirstName1 { get; set; }
        public decimal ProcAmount { get; set; }
        public decimal OOPAmount { get; set; }
        public decimal CancAmount { get; set; }
        public decimal PendAmount { get; set; }
        public Nullable<decimal> saDownPaymentPercentage { get; set; }
        public Nullable<decimal> saDownPaymentPaidPercentage { get; set; }
        public string saComments { get; set; }
        public Nullable<decimal> TotalProcAmount { get; set; }
        public Nullable<decimal> saDownPayment { get; set; }
        public Nullable<decimal> saDownPaymentPaid { get; set; }
    }
}
