//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptMealTickets
    {
        public int meID { get; set; }
        public System.DateTime meD { get; set; }
        public int megu { get; set; }
        public int meQty { get; set; }
        public string myN { get; set; }
        public int meAdults { get; set; }
        public int meMinors { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string meFolios { get; set; }
        public string meComments { get; set; }
        public string guLastName1 { get; set; }
        public string guloInfo { get; set; }
        public string guEntryHost { get; set; }
        public Nullable<bool> guShow { get; set; }
        public string guEntryHostN { get; set; }
        public string guPRInvit1 { get; set; }
        public string guPRInvit1N { get; set; }
        public string guLiner1 { get; set; }
        public string guLiner1N { get; set; }
        public int mera { get; set; }
        public string RateTypeN { get; set; }
        public string mepe { get; set; }
        public string peCollaboratorID { get; set; }
        public string peN { get; set; }
        public string agN { get; set; }
        public string merep { get; set; }
    }
}
