//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptMealTicketsCost
    {
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public Nullable<int> Adults { get; set; }
        public Nullable<int> Minors { get; set; }
        public Nullable<decimal> AdultsAmount { get; set; }
        public Nullable<decimal> MinorsAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
