//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptPremanifestOuthouse
    {
        public string srN { get; set; }
        public int guID { get; set; }
        public string guOutInvitNum { get; set; }
        public string Deposit { get; set; }
        public string guHotel { get; set; }
        public string guRoomNum { get; set; }
        public string guLastName1 { get; set; }
        public string guFirstName1 { get; set; }
        public string guco { get; set; }
        public string coN { get; set; }
        public Nullable<System.DateTime> guBookD { get; set; }
        public Nullable<System.DateTime> guBookT { get; set; }
        public string guPRInvit1 { get; set; }
        public bool guShow { get; set; }
        public bool guSale { get; set; }
        public string guComments { get; set; }
    }
}
