//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptProductionByPRSalesRoomOuthouse
    {
        public string PR { get; set; }
        public string PRN { get; set; }
        public string Status { get; set; }
        public string SalesRoomID { get; set; }
        public string SalesRoomN { get; set; }
        public Nullable<decimal> Books { get; set; }
        public Nullable<decimal> InOuts { get; set; }
        public Nullable<decimal> GrossBooks { get; set; }
        public Nullable<decimal> GrossShows { get; set; }
        public Nullable<decimal> ShowsFactor { get; set; }
        public Nullable<decimal> Directs { get; set; }
        public Nullable<decimal> WalkOuts { get; set; }
        public Nullable<decimal> CourtesyTours { get; set; }
        public Nullable<decimal> SaveTours { get; set; }
        public Nullable<decimal> Shows { get; set; }
        public Nullable<decimal> Sales_TOTAL { get; set; }
        public Nullable<decimal> SalesAmount_TOTAL { get; set; }
        public Nullable<decimal> Sales_PROC { get; set; }
        public Nullable<decimal> SalesAmount_PROC { get; set; }
        public Nullable<decimal> Sales_OOP { get; set; }
        public Nullable<decimal> SalesAmount_OOP { get; set; }
        public Nullable<decimal> Sales_PEND { get; set; }
        public Nullable<decimal> SalesAmount_PEND { get; set; }
        public Nullable<decimal> Sales_CANCEL { get; set; }
        public Nullable<decimal> SalesAmount_CANCEL { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> CancelFactor { get; set; }
        public Nullable<decimal> ClosingFactor { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<decimal> AverageSale { get; set; }
    }
}
