//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptProductionByPRInhouse
    {
        public string Location { get; set; }
        public string Team { get; set; }
        public string Leader { get; set; }
        public string PRID { get; set; }
        public string PRN { get; set; }
        public string Status { get; set; }
        public Nullable<int> Assigns { get; set; }
        public Nullable<decimal> Contacts { get; set; }
        public Nullable<decimal> ContactsFactor { get; set; }
        public Nullable<decimal> Availables { get; set; }
        public Nullable<decimal> AvailablesFactor { get; set; }
        public Nullable<decimal> BooksNoDirects { get; set; }
        public Nullable<decimal> Directs { get; set; }
        public Nullable<decimal> Books { get; set; }
        public Nullable<decimal> BooksFactor { get; set; }
        public Nullable<decimal> ShowsNoDirects { get; set; }
        public Nullable<decimal> ShowsFactor { get; set; }
        public Nullable<decimal> Shows { get; set; }
        public Nullable<decimal> InOuts { get; set; }
        public Nullable<decimal> WalkOuts { get; set; }
        public Nullable<decimal> Tours { get; set; }
        public Nullable<decimal> CourtesyTours { get; set; }
        public Nullable<decimal> SaveTours { get; set; }
        public Nullable<decimal> TotalTours { get; set; }
        public Nullable<decimal> UPS { get; set; }
        public Nullable<decimal> Sales_PROC { get; set; }
        public Nullable<decimal> SalesAmount_PROC { get; set; }
        public Nullable<decimal> Sales_PEND { get; set; }
        public Nullable<decimal> SalesAmount_PEND { get; set; }
        public Nullable<decimal> Sales_OOP { get; set; }
        public Nullable<decimal> SalesAmount_OOP { get; set; }
        public Nullable<decimal> ClosingFactor { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<decimal> AverageSale { get; set; }
    }
}
