//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptProductionBySalesRoomMarket
    {
        public string SalesRoom { get; set; }
        public string Market { get; set; }
        public Nullable<int> GrossBooks { get; set; }
        public Nullable<int> Directs { get; set; }
        public Nullable<int> Books { get; set; }
        public Nullable<int> GrossShows { get; set; }
        public Nullable<int> Shows { get; set; }
        public Nullable<decimal> ShowsFactor { get; set; }
        public Nullable<int> Sales { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<decimal> ClosingFactor { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<decimal> AverageSale { get; set; }
    }
}
