//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptProductionByPRGroupInhouse
    {
        public string PR { get; set; }
        public string PRN { get; set; }
        public string Type { get; set; }
        public Nullable<int> Groups { get; set; }
        public Nullable<int> Integrants { get; set; }
        public Nullable<int> TotalIntegrants { get; set; }
        public Nullable<int> Assigns { get; set; }
        public Nullable<decimal> Contacts { get; set; }
        public Nullable<decimal> ContactsFactor { get; set; }
        public Nullable<decimal> Availables { get; set; }
        public Nullable<decimal> AvailablesFactor { get; set; }
        public Nullable<decimal> GrossBooks { get; set; }
        public Nullable<decimal> Directs { get; set; }
        public Nullable<decimal> Books { get; set; }
        public Nullable<decimal> BooksFactor { get; set; }
        public Nullable<decimal> GrossShows { get; set; }
        public Nullable<decimal> Shows { get; set; }
        public Nullable<decimal> ShowsFactor { get; set; }
        public Nullable<decimal> Sales_TOTAL { get; set; }
        public Nullable<decimal> SalesAmount_TOTAL { get; set; }
        public Nullable<decimal> Sales_PR { get; set; }
        public Nullable<decimal> SalesAmount_PR { get; set; }
        public Nullable<decimal> Sales_SELFGEN { get; set; }
        public Nullable<decimal> SalesAmount_SELFGEN { get; set; }
        public Nullable<decimal> ClosingFactor { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<decimal> AverageSale { get; set; }
    }
}
