//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptPremanifestWithGifts
    {
        public string srN { get; set; }
        public string loN { get; set; }
        public int guID { get; set; }
        public string guls { get; set; }
        public string guRoomNum { get; set; }
        public string guLastName1 { get; set; }
        public string guco { get; set; }
        public string coN { get; set; }
        public string guHotel { get; set; }
        public Nullable<decimal> guPax { get; set; }
        public Nullable<System.DateTime> guInvitD { get; set; }
        public Nullable<System.DateTime> guInvitT { get; set; }
        public Nullable<System.DateTime> guReschDT { get; set; }
        public System.DateTime guCheckInD { get; set; }
        public System.DateTime guCheckOutD { get; set; }
        public string guag { get; set; }
        public string agN { get; set; }
        public string guComments { get; set; }
        public Nullable<System.DateTime> guBookT { get; set; }
        public string guPRInvit1 { get; set; }
        public string guO2 { get; set; }
        public string guCCType { get; set; }
        public string guShow { get; set; }
        public string guSale { get; set; }
        public bool guBookCanc { get; set; }
        public string Gifts { get; set; }
    }
}
