//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptProductionByLeadSourceMarketMonthly
    {
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string MonthN { get; set; }
        public Nullable<bool> MarketTotal { get; set; }
        public string Market { get; set; }
        public string LeadSource { get; set; }
        public string Program { get; set; }
        public Nullable<int> Arrivals { get; set; }
        public Nullable<int> Contacts { get; set; }
        public Nullable<decimal> ContactsFactor { get; set; }
        public Nullable<int> Availables { get; set; }
        public Nullable<decimal> AvailablesFactor { get; set; }
        public Nullable<int> GrossBooks { get; set; }
        public Nullable<int> Books { get; set; }
        public Nullable<decimal> BooksFactor { get; set; }
        public Nullable<int> GrossShows { get; set; }
        public Nullable<int> Shows { get; set; }
        public Nullable<decimal> ShowsFactor { get; set; }
        public Nullable<decimal> ShowsArrivalsFactor { get; set; }
        public Nullable<int> Sales { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<decimal> ClosingFactor { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<int> Directs { get; set; }
        public Nullable<int> InOuts { get; set; }
        public Nullable<int> WalkOuts { get; set; }
        public Nullable<int> Tours { get; set; }
        public Nullable<int> CourtesyTours { get; set; }
        public Nullable<int> SaveTours { get; set; }
        public Nullable<int> TotalTours { get; set; }
        public Nullable<int> UPS { get; set; }
        public Nullable<decimal> AverageSale { get; set; }
    }
}
