//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptPRStats
    {
        public string PR_ID { get; set; }
        public string PR_NAME { get; set; }
        public Nullable<int> Assign { get; set; }
        public Nullable<decimal> Conts { get; set; }
        public Nullable<decimal> C_Factor { get; set; }
        public Nullable<decimal> Avails { get; set; }
        public Nullable<decimal> A_Factor { get; set; }
        public Nullable<decimal> Bk { get; set; }
        public Nullable<decimal> Bk_Factor { get; set; }
        public Nullable<decimal> Dep { get; set; }
        public Nullable<decimal> Dir { get; set; }
        public Nullable<decimal> Sh { get; set; }
        public Nullable<decimal> IO { get; set; }
        public Nullable<decimal> Sh_Factor { get; set; }
        public Nullable<decimal> TSh { get; set; }
        public Nullable<decimal> SG { get; set; }
        public Nullable<decimal> Proc_Number { get; set; }
        public Nullable<decimal> Processable { get; set; }
        public Nullable<decimal> OutP_Number { get; set; }
        public Nullable<decimal> Out_Pending { get; set; }
        public Nullable<decimal> C_Number { get; set; }
        public Nullable<decimal> Cancelled { get; set; }
        public Nullable<decimal> Total_Number { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Proc_PR_Number { get; set; }
        public Nullable<decimal> Proc_PR { get; set; }
        public Nullable<decimal> Proc_SG_Number { get; set; }
        public Nullable<decimal> Proc_SG { get; set; }
        public Nullable<decimal> Eff { get; set; }
        public Nullable<decimal> Cl_Factor { get; set; }
        public Nullable<decimal> Ca_Factor { get; set; }
        public Nullable<decimal> Avg_Sale { get; set; }
        public string P_Status { get; set; }
        public Nullable<decimal> T_Books { get; set; }
    }
}
