//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptRefundLetter_BookingDeposit
    {
        public decimal Amount { get; set; }
        public string AmountLetter { get; set; }
        public string Currency { get; set; }
        public string CCType { get; set; }
        public Nullable<int> CardNum { get; set; }
        public string ExpDate { get; set; }
        public string Auth { get; set; }
    }
}
