//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptRepsPayment
    {
        public int guID { get; set; }
        public string agrp { get; set; }
        public string guag { get; set; }
        public Nullable<System.DateTime> guBookD { get; set; }
        public string GuestName { get; set; }
        public string Q { get; set; }
        public decimal agShowPay { get; set; }
        public Nullable<int> agSale { get; set; }
        public decimal agSalePay { get; set; }
        public Nullable<decimal> agTotalSalePay { get; set; }
        public decimal agTotalPay { get; set; }
        public bool guInOut { get; set; }
        public bool guWalkOut { get; set; }
    }
}
