//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptStatisticsByFTBCategories
    {
        public string SalemanID { get; set; }
        public string SalemanName { get; set; }
        public string Locations { get; set; }
        public string SalemanType { get; set; }
        public string SalemanTypeN { get; set; }
        public string PostName { get; set; }
        public string TeamN { get; set; }
        public string TeamLeaderN { get; set; }
        public string SalesmanStatus { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<int> OPP { get; set; }
        public Nullable<decimal> UPS { get; set; }
        public Nullable<decimal> SalesRegular { get; set; }
        public Nullable<decimal> SalesExit { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<decimal> ClosingFactor { get; set; }
        public Nullable<decimal> SaleAverage { get; set; }
    }
}
