//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptStatsBySegment
    {
        public string SalemanID { get; set; }
        public string SalemanName { get; set; }
        public string SalemanType { get; set; }
        public string SegmentN { get; set; }
        public string TeamN { get; set; }
        public string TeamLeaderN { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> UPS { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<decimal> ClosingFactor { get; set; }
    }
}
