//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptShowFactorByBookingDate
    {
        public string Agency { get; set; }
        public string AgencyN { get; set; }
        public Nullable<int> DaysDifference { get; set; }
        public Nullable<int> Difference { get; set; }
        public Nullable<int> Books { get; set; }
        public Nullable<int> Shows { get; set; }
        public Nullable<decimal> ShowsFactor { get; set; }
        public Nullable<int> InOuts { get; set; }
        public Nullable<int> WalkOuts { get; set; }
        public Nullable<int> Group { get; set; }
    }
}
