//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptSelfGen
    {
        public string guPRInvit1 { get; set; }
        public string peN { get; set; }
        public string peps { get; set; }
        public Nullable<System.DateTime> guShowD { get; set; }
        public bool guShow { get; set; }
        public bool guInOut { get; set; }
        public bool guWalkOut { get; set; }
    }
}
