//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptTaxisIn
    {
        public string ShowType { get; set; }
        public int guID { get; set; }
        public string guloInvit { get; set; }
        public Nullable<System.DateTime> guShowD { get; set; }
        public string guGuest { get; set; }
        public decimal guPax { get; set; }
        public decimal Adults { get; set; }
        public Nullable<int> Minors { get; set; }
        public string guHotel { get; set; }
        public string guPRInvit1 { get; set; }
        public decimal guTaxiIn { get; set; }
        public string guEntryHost { get; set; }
        public string guWComments { get; set; }
    }
}
