//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptUnavailableMotivesByAgency
    {
        public Nullable<byte> umID { get; set; }
        public string UnavailMot { get; set; }
        public string mkID { get; set; }
        public string Market { get; set; }
        public string agID { get; set; }
        public string Agency { get; set; }
        public Nullable<int> Arrivals { get; set; }
        public Nullable<decimal> ArrivalsPercentage { get; set; }
        public Nullable<int> ByUser { get; set; }
    }
}
