//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptWeeklyMonthlyHostess_ByPR
    {
        public string Type { get; set; }
        public string guls { get; set; }
        public string guloInvit { get; set; }
        public Nullable<int> guDirect { get; set; }
        public Nullable<int> guInOut { get; set; }
        public Nullable<int> guWalkOut { get; set; }
        public string guPRInvit { get; set; }
        public string guPRInvitN { get; set; }
        public string gusr { get; set; }
    }
}
