//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class RptWeeklyMonthlyHostess_ByTourTime
    {
        public string guls { get; set; }
        public Nullable<System.DateTime> guD { get; set; }
        public string Time { get; set; }
        public Nullable<int> guBook { get; set; }
        public Nullable<int> guShow { get; set; }
        public Nullable<int> guDirect { get; set; }
    }
}
