//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRoom
    {
        public string srID { get; set; }
        public string srN { get; set; }
        public short srHoursDif { get; set; }
        public string srAddOut { get; set; }
        public bool srDBMaint { get; set; }
        public string srWH { get; set; }
        public string srar { get; set; }
        public bool srA { get; set; }
        public string srcu { get; set; }
        public System.DateTime srGiftsRcptCloseD { get; set; }
        public System.DateTime srCxCCloseD { get; set; }
        public bool srAppointment { get; set; }
        public string srBoss { get; set; }
        public System.DateTime srShowsCloseD { get; set; }
        public System.DateTime srMealTicketsCloseD { get; set; }
        public System.DateTime srSalesCloseD { get; set; }
        public string srPropertyOpera { get; set; }
        public bool srUseSistur { get; set; }
        public string srCECOID { get; set; }
        public string srCEBEID { get; set; }
    }
}
