//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesRoom()
        {
            this.Efficiencies = new HashSet<Efficiency>();
            this.GiftsReceipts = new HashSet<GiftsReceipt>();
            this.MealTicketFolios = new HashSet<MealTicketFolio>();
            this.MealTickets = new HashSet<MealTicket>();
            this.Sales = new HashSet<Sale>();
            this.SalesLogs = new HashSet<SaleLog>();
            this.SalesRoomsLogs = new HashSet<SalesRoomLog>();
            this.TeamsSalesmen = new HashSet<TeamSalesmen>();
            this.TourTimesBySalesRoomWeekDays = new HashSet<TourTimeBySalesRoomWeekDay>();
            this.Banks = new HashSet<Bank>();
        }
    
        public string srID { get; set; }
        public string srN { get; set; }
        public short srHoursDif { get; set; }
        public string srAddOut { get; set; }
        public bool srDBMaint { get; set; }
        public string srWH { get; set; }
        public string srar { get; set; }
        public bool srA { get; set; }
        public string srcu { get; set; }
        public System.DateTime srGiftsRcptCloseD { get; set; }
        public System.DateTime srCxCCloseD { get; set; }
        public bool srAppointment { get; set; }
        public string srBoss { get; set; }
        public System.DateTime srShowsCloseD { get; set; }
        public System.DateTime srMealTicketsCloseD { get; set; }
        public System.DateTime srSalesCloseD { get; set; }
        public string srPropertyOpera { get; set; }
        public bool srUseSistur { get; set; }
        public string srCECOID { get; set; }
        public string srCEBEID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Efficiency> Efficiencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsReceipt> GiftsReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealTicketFolio> MealTicketFolios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealTicket> MealTickets { get; set; }
        public virtual Personnel Personnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleLog> SalesLogs { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesRoomLog> SalesRoomsLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamSalesmen> TeamsSalesmen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourTimeBySalesRoomWeekDay> TourTimesBySalesRoomWeekDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bank> Banks { get; set; }
    }
}
