//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    
    public partial class SaleByCloser
    {
        public int saID { get; set; }
        public string sals { get; set; }
        public string sasr { get; set; }
        public string saMembershipNum { get; set; }
        public string stN { get; set; }
        public System.DateTime saD { get; set; }
        public Nullable<System.DateTime> saProcD { get; set; }
        public string saLastName1 { get; set; }
        public string saCloser1 { get; set; }
        public string Closer1N { get; set; }
        public string saCloser2 { get; set; }
        public string Closer2N { get; set; }
        public string saCloser3 { get; set; }
        public string Closer3N { get; set; }
        public string saExit1 { get; set; }
        public string Exit1N { get; set; }
        public string saExit2 { get; set; }
        public string Exit2N { get; set; }
        public decimal saGrossAmount { get; set; }
        public bool saCancel { get; set; }
        public Nullable<System.DateTime> saCancelD { get; set; }
    }
}
