//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleLog
    {
        public System.DateTime slID { get; set; }
        public int slsa { get; set; }
        public string slMembershipNum { get; set; }
        public Nullable<int> slgu { get; set; }
        public string slst { get; set; }
        public Nullable<int> slReference { get; set; }
        public string slmt { get; set; }
        public Nullable<decimal> slOriginalAmount { get; set; }
        public Nullable<decimal> slNewAmount { get; set; }
        public Nullable<decimal> slGrossAmount { get; set; }
        public System.DateTime slD { get; set; }
        public Nullable<System.DateTime> slProcD { get; set; }
        public Nullable<System.DateTime> slCancelD { get; set; }
        public string sllo { get; set; }
        public string slls { get; set; }
        public string slsr { get; set; }
        public string slPR1 { get; set; }
        public Nullable<bool> slSelfGen { get; set; }
        public string slPR2 { get; set; }
        public string slPR3 { get; set; }
        public string slPRCaptain1 { get; set; }
        public string slPRCaptain2 { get; set; }
        public Nullable<byte> slLiner1Type { get; set; }
        public string slLiner1 { get; set; }
        public string slLiner2 { get; set; }
        public string slLinerCaptain1 { get; set; }
        public string slCloser1 { get; set; }
        public string slCloser2 { get; set; }
        public string slCloser3 { get; set; }
        public string slExit1 { get; set; }
        public string slExit2 { get; set; }
        public string slCloserCaptain1 { get; set; }
        public string slPodium { get; set; }
        public string slVLO { get; set; }
        public Nullable<byte> slCloser1P { get; set; }
        public Nullable<byte> slCloser2P { get; set; }
        public Nullable<byte> slCloser3P { get; set; }
        public Nullable<byte> slExit1P { get; set; }
        public Nullable<byte> slExit2P { get; set; }
        public Nullable<decimal> slClosingCost { get; set; }
        public Nullable<decimal> slOverPack { get; set; }
        public string slChangedBy { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual LeadSource LeadSource { get; set; }
        public virtual Location Location { get; set; }
        public virtual MembershipType MembershipType { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Personnel Personnel1 { get; set; }
        public virtual Personnel Personnel2 { get; set; }
        public virtual Personnel Personnel3 { get; set; }
        public virtual Personnel Personnel4 { get; set; }
        public virtual Personnel Personnel5 { get; set; }
        public virtual Personnel Personnel6 { get; set; }
        public virtual Personnel Personnel7 { get; set; }
        public virtual Personnel Personnel8 { get; set; }
        public virtual Personnel Personnel9 { get; set; }
        public virtual Personnel Personnel10 { get; set; }
        public virtual Personnel Personnel11 { get; set; }
        public virtual Personnel Personnel12 { get; set; }
        public virtual Personnel Personnel13 { get; set; }
        public virtual Personnel Personnel14 { get; set; }
        public virtual Personnel Personnel15 { get; set; }
        public virtual Personnel Personnel16 { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Sale Sale1 { get; set; }
        public virtual SalesRoom SalesRoom { get; set; }
        public virtual SaleType SaleType { get; set; }
    }
}
