//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleLog
    {
        public System.DateTime slID { get; set; }
        public int slsa { get; set; }
        public string slMembershipNum { get; set; }
        public Nullable<int> slgu { get; set; }
        public string slst { get; set; }
        public Nullable<int> slReference { get; set; }
        public string slmt { get; set; }
        public Nullable<decimal> slOriginalAmount { get; set; }
        public Nullable<decimal> slNewAmount { get; set; }
        public Nullable<decimal> slGrossAmount { get; set; }
        public System.DateTime slD { get; set; }
        public Nullable<System.DateTime> slProcD { get; set; }
        public Nullable<System.DateTime> slCancelD { get; set; }
        public string sllo { get; set; }
        public string slls { get; set; }
        public string slsr { get; set; }
        public string slPR1 { get; set; }
        public Nullable<bool> slSelfGen { get; set; }
        public string slPR2 { get; set; }
        public string slPR3 { get; set; }
        public string slPRCaptain1 { get; set; }
        public string slPRCaptain2 { get; set; }
        public Nullable<byte> slLiner1Type { get; set; }
        public string slLiner1 { get; set; }
        public string slLiner2 { get; set; }
        public string slLinerCaptain1 { get; set; }
        public string slCloser1 { get; set; }
        public string slCloser2 { get; set; }
        public string slCloser3 { get; set; }
        public string slExit1 { get; set; }
        public string slExit2 { get; set; }
        public string slCloserCaptain1 { get; set; }
        public string slPodium { get; set; }
        public string slVLO { get; set; }
        public Nullable<byte> slCloser1P { get; set; }
        public Nullable<byte> slCloser2P { get; set; }
        public Nullable<byte> slCloser3P { get; set; }
        public Nullable<byte> slExit1P { get; set; }
        public Nullable<byte> slExit2P { get; set; }
        public Nullable<decimal> slClosingCost { get; set; }
        public Nullable<decimal> slOverPack { get; set; }
        public string slChangedBy { get; set; }
        public string slLiner3 { get; set; }
        public string slCloser4 { get; set; }
        public string slExit3 { get; set; }
        public string slFTB1 { get; set; }
        public string slFTB2 { get; set; }
        public string slFTM1 { get; set; }
        public string slFTM2 { get; set; }
    
        public virtual Guest Guest { internal get; set; }
        public virtual LeadSource LeadSource { internal get; set; }
        public virtual Location Location { internal get; set; }
        public virtual MembershipType MembershipType { internal get; set; }
        public virtual Personnel Personnel { internal get; set; }
        public virtual Personnel Personnel_Closer1 { internal get; set; }
        public virtual Personnel Personnel_Closer2 { internal get; set; }
        public virtual Personnel Personnel_Closer3 { internal get; set; }
        public virtual Personnel Personnel_CloserCaptain1 { internal get; set; }
        public virtual Personnel Personnel_Exit1 { internal get; set; }
        public virtual Personnel Personnel_Exit2 { internal get; set; }
        public virtual Personnel Personnel_Liner1 { internal get; set; }
        public virtual Personnel Personnel_Liner2 { internal get; set; }
        public virtual Personnel Personnel_LinerCaptain1 { internal get; set; }
        public virtual Personnel Personnel_Podium { internal get; set; }
        public virtual Personnel Personnel_PR1 { internal get; set; }
        public virtual Personnel Personnel_PR2 { internal get; set; }
        public virtual Personnel Personnel_PR3 { internal get; set; }
        public virtual Personnel Personnel_PRCaptain1 { internal get; set; }
        public virtual Personnel Personnel_PRCaptain2 { internal get; set; }
        public virtual Personnel Personnel_VLO { internal get; set; }
        public virtual Sale Sale { internal get; set; }
        public virtual Sale Sale_Reference { internal get; set; }
        public virtual SalesRoom SalesRoom { internal get; set; }
        public virtual SaleType SaleType { internal get; set; }
        public virtual Personnel Personnel_Closer4 { get; set; }
        public virtual Personnel Personnel_Exit3 { get; set; }
        public virtual Personnel Personnel_FTB1 { get; set; }
        public virtual Personnel Personnel_FTB2 { get; set; }
        public virtual Personnel Personnel_FTM1 { get; set; }
        public virtual Personnel Personnel_FTM2 { get; set; }
        public virtual Personnel Personnel_Liner3 { get; set; }
    }
}
