//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesRoom()
        {
            this.srHoursDif = 0;
            this.srDBMaint = false;
            this.srA = true;
            this.srcu = "US";
            this.srUseSistur = true;
            this.Efficiencies = new HashSet<Efficiency>();
            this.GiftsReceipts = new HashSet<GiftsReceipt>();
            this.MealTicketsFolios = new HashSet<MealTicketFolio>();
            this.MealTickets = new HashSet<MealTicket>();
            this.Sales = new HashSet<Sale>();
            this.SalesLogs = new HashSet<SaleLog>();
            this.SalesRoomsLogs = new HashSet<SalesRoomLog>();
            this.TeamsSalesmen = new HashSet<TeamSalesmen>();
            this.TourTimesBySalesRoomWeekDay = new HashSet<TourTimeBySalesRoomWeekDay>();
            this.Banks = new HashSet<Bank>();
            this.LeadSources = new HashSet<LeadSource>();
        }
    
        public string srID { get; set; }
        public string srN { get; set; }
        public short srHoursDif { get; set; }
        public string srAddOut { get; set; }
        public bool srDBMaint { get; set; }
        public string srWH { get; set; }
        public string srar { get; set; }
        public bool srA { get; set; }
        public string srcu { get; set; }
        public System.DateTime srGiftsRcptCloseD { get; set; }
        public System.DateTime srCxCCloseD { get; set; }
        public bool srAppointment { get; set; }
        public string srBoss { get; set; }
        public System.DateTime srShowsCloseD { get; set; }
        public System.DateTime srMealTicketsCloseD { get; set; }
        public System.DateTime srSalesCloseD { get; set; }
        public string srPropertyOpera { get; set; }
        public bool srUseSistur { get; set; }
        public string srzn { get; set; }
    
        public virtual Area Area { internal get; set; }
        public virtual Currency Currency { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Efficiency> Efficiencies { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsReceipt> GiftsReceipts { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealTicketFolio> MealTicketsFolios { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealTicket> MealTickets { internal get; set; }
        public virtual Personnel Personnel { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleLog> SalesLogs { internal get; set; }
        public virtual Warehouse Warehouse { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesRoomLog> SalesRoomsLogs { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamSalesmen> TeamsSalesmen { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourTimeBySalesRoomWeekDay> TourTimesBySalesRoomWeekDay { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bank> Banks { internal get; set; }
        public virtual Zone Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadSource> LeadSources { get; set; }
    }
}
