//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesAmountRange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesAmountRange()
        {
            this.snA = true;
        }
    
        public int snID { get; set; }
        public string snN { get; set; }
        public decimal snFrom { get; set; }
        public decimal snTo { get; set; }
        public bool snA { get; set; }
    }
}
