//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreRuleDetail
    {
        public byte sisu { get; set; }
        public byte sisp { get; set; }
        public decimal siScore { get; set; }
    
        public virtual ScoreRule ScoreRule { get; set; }
        public virtual ScoreRuleConcept ScoreRulesConcept { get; set; }
    }
}
