//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreRuleByLeadSource
    {
        public string sbls { get; set; }
        public bool sbA { get; set; }
    
        public virtual LeadSource LeadSource { get; set; }
    }
}
