//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonDate
    {
        public string sdss { get; set; }
        public System.DateTime sdStartD { get; set; }
        public System.DateTime sdEndD { get; set; }
    
        public virtual Season Season { internal get; set; }
    }
}
