//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShowProgram()
        {
            this.skA = true;
        }
    
        public string skID { get; set; }
        public string skN { get; set; }
        public bool skA { get; set; }
        public string sksg { get; set; }
    
        public virtual ShowProgramCategory ShowProgramCategory { internal get; set; }
    }
}
