//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSalesmen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamSalesmen()
        {
            this.tsA = true;
        }
    
        public string tssr { get; set; }
        public string tsID { get; set; }
        public string tsN { get; set; }
        public string tsLeader { get; set; }
        public bool tsA { get; set; }
    
        public virtual Personnel Personnel { internal get; set; }
        public virtual SalesRoom SalesRoom { internal get; set; }
    }
}
