//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wholesaler
    {
        public int wscl { get; set; }
        public decimal wsCompany { get; set; }
        public string wsApplication { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
