//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.BusinessRules.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int USP_OR_RptFollowUpByAgency_Timeout {
            get {
                return ((int)(this["USP_OR_RptFollowUpByAgency_Timeout"]));
            }
            set {
                this["USP_OR_RptFollowUpByAgency_Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int USP_OR_RptFollowUpByPR_Timeout {
            get {
                return ((int)(this["USP_OR_RptFollowUpByPR_Timeout"]));
            }
            set {
                this["USP_OR_RptFollowUpByPR_Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int USP_OR_RptProductionByAgeInhouse_Timeout {
            get {
                return ((int)(this["USP_OR_RptProductionByAgeInhouse_Timeout"]));
            }
            set {
                this["USP_OR_RptProductionByAgeInhouse_Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int USP_OR_RptProductionByAgeMarketOriginallyAvailableInhouse_Timeout {
            get {
                return ((int)(this["USP_OR_RptProductionByAgeMarketOriginallyAvailableInhouse_Timeout"]));
            }
            set {
                this["USP_OR_RptProductionByAgeMarketOriginallyAvailableInhouse_Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int USP_OR_RptProductionByAgencyInhouse_Timeout {
            get {
                return ((int)(this["USP_OR_RptProductionByAgencyInhouse_Timeout"]));
            }
            set {
                this["USP_OR_RptProductionByAgencyInhouse_Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int USP_OR_RptPRStats {
            get {
                return ((int)(this["USP_OR_RptPRStats"]));
            }
            set {
                this["USP_OR_RptPRStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int UPS_OR_RptProductionBySalesRoom {
            get {
                return ((int)(this["UPS_OR_RptProductionBySalesRoom"]));
            }
            set {
                this["UPS_OR_RptProductionBySalesRoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int UPS_OR_RptProductionBySalesRoomMarket {
            get {
                return ((int)(this["UPS_OR_RptProductionBySalesRoomMarket"]));
            }
            set {
                this["UPS_OR_RptProductionBySalesRoomMarket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int UPS_OR_RptProductionBySalesRoomMarketSubmarket {
            get {
                return ((int)(this["UPS_OR_RptProductionBySalesRoomMarketSubmarket"]));
            }
            set {
                this["UPS_OR_RptProductionBySalesRoomMarketSubmarket"] = value;
            }
        }
    }
}
