//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IM.Services.SisturService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PromocionesControllerBinding", Namespace="urn:PromocionesControllerwsdl")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ConsumosPromocionesListResponse))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(BeneficiosxFolioResponse))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(PromoForzadaFolioTipoResponse))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(PromocionesTipoResponse))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OstdtpromosResponse))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OstpromosResponse))]
    public partial class PromocionesControllerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerCabeceraEstadoCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDetalleEstadoCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPromocionesTipoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPromocionesForzadasFolioTipoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizaEstatusPromoForzadaFolioOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarPromocionForzadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerBeneficiosByFolioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPromocionesConsumidasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PromocionesControllerService() {
            this.Url = global::IM.Services.Properties.Settings.Default.IM_Services_SisturService_PromocionesControllerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerCabeceraEstadoCuentaCompletedEventHandler ObtenerCabeceraEstadoCuentaCompleted;
        
        /// <remarks/>
        public event ObtenerDetalleEstadoCuentaCompletedEventHandler ObtenerDetalleEstadoCuentaCompleted;
        
        /// <remarks/>
        public event ObtenerPromocionesTipoCompletedEventHandler ObtenerPromocionesTipoCompleted;
        
        /// <remarks/>
        public event ObtenerPromocionesForzadasFolioTipoCompletedEventHandler ObtenerPromocionesForzadasFolioTipoCompleted;
        
        /// <remarks/>
        public event ActualizaEstatusPromoForzadaFolioCompletedEventHandler ActualizaEstatusPromoForzadaFolioCompleted;
        
        /// <remarks/>
        public event GuardarPromocionForzadaCompletedEventHandler GuardarPromocionForzadaCompleted;
        
        /// <remarks/>
        public event ObtenerBeneficiosByFolioCompletedEventHandler ObtenerBeneficiosByFolioCompleted;
        
        /// <remarks/>
        public event ConsultarPromocionesConsumidasCompletedEventHandler ConsultarPromocionesConsumidasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PromocionesControllerwsdl#ObtenerCabeceraEstadoCuenta", RequestNamespace="urn:PromocionesControllerwsdl", ResponseNamespace="urn:PromocionesControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public OstpromosResponse[] ObtenerCabeceraEstadoCuenta(BeneficiosxFolioRequest request) {
            object[] results = this.Invoke("ObtenerCabeceraEstadoCuenta", new object[] {
                        request});
            return ((OstpromosResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCabeceraEstadoCuentaAsync(BeneficiosxFolioRequest request) {
            this.ObtenerCabeceraEstadoCuentaAsync(request, null);
        }
        
        /// <remarks/>
        public void ObtenerCabeceraEstadoCuentaAsync(BeneficiosxFolioRequest request, object userState) {
            if ((this.ObtenerCabeceraEstadoCuentaOperationCompleted == null)) {
                this.ObtenerCabeceraEstadoCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCabeceraEstadoCuentaOperationCompleted);
            }
            this.InvokeAsync("ObtenerCabeceraEstadoCuenta", new object[] {
                        request}, this.ObtenerCabeceraEstadoCuentaOperationCompleted, userState);
        }
        
        private void OnObtenerCabeceraEstadoCuentaOperationCompleted(object arg) {
            if ((this.ObtenerCabeceraEstadoCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCabeceraEstadoCuentaCompleted(this, new ObtenerCabeceraEstadoCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PromocionesControllerwsdl#ObtenerDetalleEstadoCuenta", RequestNamespace="urn:PromocionesControllerwsdl", ResponseNamespace="urn:PromocionesControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public OstdtpromosResponse[] ObtenerDetalleEstadoCuenta(OstdtpromosRequest OstdtpromosRequest) {
            object[] results = this.Invoke("ObtenerDetalleEstadoCuenta", new object[] {
                        OstdtpromosRequest});
            return ((OstdtpromosResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDetalleEstadoCuentaAsync(OstdtpromosRequest OstdtpromosRequest) {
            this.ObtenerDetalleEstadoCuentaAsync(OstdtpromosRequest, null);
        }
        
        /// <remarks/>
        public void ObtenerDetalleEstadoCuentaAsync(OstdtpromosRequest OstdtpromosRequest, object userState) {
            if ((this.ObtenerDetalleEstadoCuentaOperationCompleted == null)) {
                this.ObtenerDetalleEstadoCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDetalleEstadoCuentaOperationCompleted);
            }
            this.InvokeAsync("ObtenerDetalleEstadoCuenta", new object[] {
                        OstdtpromosRequest}, this.ObtenerDetalleEstadoCuentaOperationCompleted, userState);
        }
        
        private void OnObtenerDetalleEstadoCuentaOperationCompleted(object arg) {
            if ((this.ObtenerDetalleEstadoCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDetalleEstadoCuentaCompleted(this, new ObtenerDetalleEstadoCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PromocionesControllerwsdl#ObtenerPromocionesTipo", RequestNamespace="urn:PromocionesControllerwsdl", ResponseNamespace="urn:PromocionesControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public PromocionesTipoResponse[] ObtenerPromocionesTipo(PromocionesTipoRequest request) {
            object[] results = this.Invoke("ObtenerPromocionesTipo", new object[] {
                        request});
            return ((PromocionesTipoResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPromocionesTipoAsync(PromocionesTipoRequest request) {
            this.ObtenerPromocionesTipoAsync(request, null);
        }
        
        /// <remarks/>
        public void ObtenerPromocionesTipoAsync(PromocionesTipoRequest request, object userState) {
            if ((this.ObtenerPromocionesTipoOperationCompleted == null)) {
                this.ObtenerPromocionesTipoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPromocionesTipoOperationCompleted);
            }
            this.InvokeAsync("ObtenerPromocionesTipo", new object[] {
                        request}, this.ObtenerPromocionesTipoOperationCompleted, userState);
        }
        
        private void OnObtenerPromocionesTipoOperationCompleted(object arg) {
            if ((this.ObtenerPromocionesTipoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPromocionesTipoCompleted(this, new ObtenerPromocionesTipoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PromocionesControllerwsdl#ObtenerPromocionesForzadasFolioTipo", RequestNamespace="urn:PromocionesControllerwsdl", ResponseNamespace="urn:PromocionesControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public PromoForzadaFolioTipoResponse[] ObtenerPromocionesForzadasFolioTipo(PromoForzadaFolioTipoRequest request) {
            object[] results = this.Invoke("ObtenerPromocionesForzadasFolioTipo", new object[] {
                        request});
            return ((PromoForzadaFolioTipoResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPromocionesForzadasFolioTipoAsync(PromoForzadaFolioTipoRequest request) {
            this.ObtenerPromocionesForzadasFolioTipoAsync(request, null);
        }
        
        /// <remarks/>
        public void ObtenerPromocionesForzadasFolioTipoAsync(PromoForzadaFolioTipoRequest request, object userState) {
            if ((this.ObtenerPromocionesForzadasFolioTipoOperationCompleted == null)) {
                this.ObtenerPromocionesForzadasFolioTipoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPromocionesForzadasFolioTipoOperationCompleted);
            }
            this.InvokeAsync("ObtenerPromocionesForzadasFolioTipo", new object[] {
                        request}, this.ObtenerPromocionesForzadasFolioTipoOperationCompleted, userState);
        }
        
        private void OnObtenerPromocionesForzadasFolioTipoOperationCompleted(object arg) {
            if ((this.ObtenerPromocionesForzadasFolioTipoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPromocionesForzadasFolioTipoCompleted(this, new ObtenerPromocionesForzadasFolioTipoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PromocionesControllerwsdl#ActualizaEstatusPromoForzadaFolio", RequestNamespace="urn:PromocionesControllerwsdl", ResponseNamespace="urn:PromocionesControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ActualizaEstatusPromoForzadaResponse ActualizaEstatusPromoForzadaFolio(ActualizaEstatusPromoForzadaRequest request) {
            object[] results = this.Invoke("ActualizaEstatusPromoForzadaFolio", new object[] {
                        request});
            return ((ActualizaEstatusPromoForzadaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizaEstatusPromoForzadaFolioAsync(ActualizaEstatusPromoForzadaRequest request) {
            this.ActualizaEstatusPromoForzadaFolioAsync(request, null);
        }
        
        /// <remarks/>
        public void ActualizaEstatusPromoForzadaFolioAsync(ActualizaEstatusPromoForzadaRequest request, object userState) {
            if ((this.ActualizaEstatusPromoForzadaFolioOperationCompleted == null)) {
                this.ActualizaEstatusPromoForzadaFolioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizaEstatusPromoForzadaFolioOperationCompleted);
            }
            this.InvokeAsync("ActualizaEstatusPromoForzadaFolio", new object[] {
                        request}, this.ActualizaEstatusPromoForzadaFolioOperationCompleted, userState);
        }
        
        private void OnActualizaEstatusPromoForzadaFolioOperationCompleted(object arg) {
            if ((this.ActualizaEstatusPromoForzadaFolioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizaEstatusPromoForzadaFolioCompleted(this, new ActualizaEstatusPromoForzadaFolioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PromocionesControllerwsdl#GuardarPromocionForzada", RequestNamespace="urn:PromocionesControllerwsdl", ResponseNamespace="urn:PromocionesControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public GuardaPromocionForzadaResponse GuardarPromocionForzada(GuardaPromocionForzadaRequest request) {
            object[] results = this.Invoke("GuardarPromocionForzada", new object[] {
                        request});
            return ((GuardaPromocionForzadaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarPromocionForzadaAsync(GuardaPromocionForzadaRequest request) {
            this.GuardarPromocionForzadaAsync(request, null);
        }
        
        /// <remarks/>
        public void GuardarPromocionForzadaAsync(GuardaPromocionForzadaRequest request, object userState) {
            if ((this.GuardarPromocionForzadaOperationCompleted == null)) {
                this.GuardarPromocionForzadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarPromocionForzadaOperationCompleted);
            }
            this.InvokeAsync("GuardarPromocionForzada", new object[] {
                        request}, this.GuardarPromocionForzadaOperationCompleted, userState);
        }
        
        private void OnGuardarPromocionForzadaOperationCompleted(object arg) {
            if ((this.GuardarPromocionForzadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarPromocionForzadaCompleted(this, new GuardarPromocionForzadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PromocionesControllerwsdl#ObtenerBeneficiosByFolio", RequestNamespace="urn:PromocionesControllerwsdl", ResponseNamespace="urn:PromocionesControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public BeneficiosxFolioResponse[] ObtenerBeneficiosByFolio(BeneficiosxFolioRequest request) {
            object[] results = this.Invoke("ObtenerBeneficiosByFolio", new object[] {
                        request});
            return ((BeneficiosxFolioResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerBeneficiosByFolioAsync(BeneficiosxFolioRequest request) {
            this.ObtenerBeneficiosByFolioAsync(request, null);
        }
        
        /// <remarks/>
        public void ObtenerBeneficiosByFolioAsync(BeneficiosxFolioRequest request, object userState) {
            if ((this.ObtenerBeneficiosByFolioOperationCompleted == null)) {
                this.ObtenerBeneficiosByFolioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerBeneficiosByFolioOperationCompleted);
            }
            this.InvokeAsync("ObtenerBeneficiosByFolio", new object[] {
                        request}, this.ObtenerBeneficiosByFolioOperationCompleted, userState);
        }
        
        private void OnObtenerBeneficiosByFolioOperationCompleted(object arg) {
            if ((this.ObtenerBeneficiosByFolioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerBeneficiosByFolioCompleted(this, new ObtenerBeneficiosByFolioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PromocionesControllerwsdl#ConsultarPromocionesConsumidas", RequestNamespace="urn:PromocionesControllerwsdl", ResponseNamespace="urn:PromocionesControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ConsumosPromocionesResponse ConsultarPromocionesConsumidas(ConsumosPromocionesRequest ConsumosPromocionesRequest) {
            object[] results = this.Invoke("ConsultarPromocionesConsumidas", new object[] {
                        ConsumosPromocionesRequest});
            return ((ConsumosPromocionesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPromocionesConsumidasAsync(ConsumosPromocionesRequest ConsumosPromocionesRequest) {
            this.ConsultarPromocionesConsumidasAsync(ConsumosPromocionesRequest, null);
        }
        
        /// <remarks/>
        public void ConsultarPromocionesConsumidasAsync(ConsumosPromocionesRequest ConsumosPromocionesRequest, object userState) {
            if ((this.ConsultarPromocionesConsumidasOperationCompleted == null)) {
                this.ConsultarPromocionesConsumidasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPromocionesConsumidasOperationCompleted);
            }
            this.InvokeAsync("ConsultarPromocionesConsumidas", new object[] {
                        ConsumosPromocionesRequest}, this.ConsultarPromocionesConsumidasOperationCompleted, userState);
        }
        
        private void OnConsultarPromocionesConsumidasOperationCompleted(object arg) {
            if ((this.ConsultarPromocionesConsumidasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPromocionesConsumidasCompleted(this, new ConsultarPromocionesConsumidasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class BeneficiosxFolioRequest {
        
        private string hotelField;
        
        private int folioField;
        
        private int roomField;
        
        private string last_nameField;
        
        private string first_nameField;
        
        private int nightsField;
        
        private string agency_cdField;
        
        private string contractField;
        
        private string guest_cdField;
        
        private string group_cdField;
        
        private string ded_commField;
        
        private string mkt_segField;
        
        private string geo_segField;
        
        private System.DateTime arv_dateField;
        
        private System.DateTime depart_dtField;
        
        private System.DateTime ent_dateField;
        
        private string rm_typeField;
        
        private int adultField;
        
        private int childField;
        
        private string countryField;
        
        private int kidField;
        
        private string chg_amt2Field;
        
        private string grat_bell_billField;
        
        private string club_statField;
        
        private int xtra_aduField;
        
        private int xtra_chdField;
        
        private int xtra_kidField;
        
        private string cvv_agencyField;
        
        private string rm_descField;
        
        private string idpromoField;
        
        /// <remarks/>
        public string hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        public int folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        public int room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
            }
        }
        
        /// <remarks/>
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
            }
        }
        
        /// <remarks/>
        public int nights {
            get {
                return this.nightsField;
            }
            set {
                this.nightsField = value;
            }
        }
        
        /// <remarks/>
        public string agency_cd {
            get {
                return this.agency_cdField;
            }
            set {
                this.agency_cdField = value;
            }
        }
        
        /// <remarks/>
        public string contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
        
        /// <remarks/>
        public string guest_cd {
            get {
                return this.guest_cdField;
            }
            set {
                this.guest_cdField = value;
            }
        }
        
        /// <remarks/>
        public string group_cd {
            get {
                return this.group_cdField;
            }
            set {
                this.group_cdField = value;
            }
        }
        
        /// <remarks/>
        public string ded_comm {
            get {
                return this.ded_commField;
            }
            set {
                this.ded_commField = value;
            }
        }
        
        /// <remarks/>
        public string mkt_seg {
            get {
                return this.mkt_segField;
            }
            set {
                this.mkt_segField = value;
            }
        }
        
        /// <remarks/>
        public string geo_seg {
            get {
                return this.geo_segField;
            }
            set {
                this.geo_segField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime arv_date {
            get {
                return this.arv_dateField;
            }
            set {
                this.arv_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime depart_dt {
            get {
                return this.depart_dtField;
            }
            set {
                this.depart_dtField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ent_date {
            get {
                return this.ent_dateField;
            }
            set {
                this.ent_dateField = value;
            }
        }
        
        /// <remarks/>
        public string rm_type {
            get {
                return this.rm_typeField;
            }
            set {
                this.rm_typeField = value;
            }
        }
        
        /// <remarks/>
        public int adult {
            get {
                return this.adultField;
            }
            set {
                this.adultField = value;
            }
        }
        
        /// <remarks/>
        public int child {
            get {
                return this.childField;
            }
            set {
                this.childField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public int kid {
            get {
                return this.kidField;
            }
            set {
                this.kidField = value;
            }
        }
        
        /// <remarks/>
        public string chg_amt2 {
            get {
                return this.chg_amt2Field;
            }
            set {
                this.chg_amt2Field = value;
            }
        }
        
        /// <remarks/>
        public string grat_bell_bill {
            get {
                return this.grat_bell_billField;
            }
            set {
                this.grat_bell_billField = value;
            }
        }
        
        /// <remarks/>
        public string club_stat {
            get {
                return this.club_statField;
            }
            set {
                this.club_statField = value;
            }
        }
        
        /// <remarks/>
        public int xtra_adu {
            get {
                return this.xtra_aduField;
            }
            set {
                this.xtra_aduField = value;
            }
        }
        
        /// <remarks/>
        public int xtra_chd {
            get {
                return this.xtra_chdField;
            }
            set {
                this.xtra_chdField = value;
            }
        }
        
        /// <remarks/>
        public int xtra_kid {
            get {
                return this.xtra_kidField;
            }
            set {
                this.xtra_kidField = value;
            }
        }
        
        /// <remarks/>
        public string cvv_agency {
            get {
                return this.cvv_agencyField;
            }
            set {
                this.cvv_agencyField = value;
            }
        }
        
        /// <remarks/>
        public string rm_desc {
            get {
                return this.rm_descField;
            }
            set {
                this.rm_descField = value;
            }
        }
        
        /// <remarks/>
        public string idpromo {
            get {
                return this.idpromoField;
            }
            set {
                this.idpromoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class ConsumosPromocionesListResponse {
        
        private string hotelField;
        
        private string folioField;
        
        private string idOp_CuponVentaField;
        
        private System.DateTime fechaPagoField;
        
        private string idPromo_PromocionField;
        
        private string numerodePromocionesUsadasField;
        
        private string paxField;
        
        private float montoFacturaField;
        
        private bool hasErrorsField;
        
        private string errorInfoField;
        
        /// <remarks/>
        public string Hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string idOp_CuponVenta {
            get {
                return this.idOp_CuponVentaField;
            }
            set {
                this.idOp_CuponVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime FechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
            }
        }
        
        /// <remarks/>
        public string idPromo_Promocion {
            get {
                return this.idPromo_PromocionField;
            }
            set {
                this.idPromo_PromocionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string NumerodePromocionesUsadas {
            get {
                return this.numerodePromocionesUsadasField;
            }
            set {
                this.numerodePromocionesUsadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Pax {
            get {
                return this.paxField;
            }
            set {
                this.paxField = value;
            }
        }
        
        /// <remarks/>
        public float MontoFactura {
            get {
                return this.montoFacturaField;
            }
            set {
                this.montoFacturaField = value;
            }
        }
        
        /// <remarks/>
        public bool HasErrors {
            get {
                return this.hasErrorsField;
            }
            set {
                this.hasErrorsField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                return this.errorInfoField;
            }
            set {
                this.errorInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class ConsumosPromocionesResponse {
        
        private ConsumosPromocionesListResponse[] listaPromocionesField;
        
        private bool hasErrorsField;
        
        private string errorInfoField;
        
        /// <remarks/>
        public ConsumosPromocionesListResponse[] listaPromociones {
            get {
                return this.listaPromocionesField;
            }
            set {
                this.listaPromocionesField = value;
            }
        }
        
        /// <remarks/>
        public bool HasErrors {
            get {
                return this.hasErrorsField;
            }
            set {
                this.hasErrorsField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                return this.errorInfoField;
            }
            set {
                this.errorInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class ConsumosPromocionesRequest {
        
        private System.DateTime fechaInicialField;
        
        private System.DateTime fechaFinalField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime FechaInicial {
            get {
                return this.fechaInicialField;
            }
            set {
                this.fechaInicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime FechaFinal {
            get {
                return this.fechaFinalField;
            }
            set {
                this.fechaFinalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class BeneficiosxFolioResponse {
        
        private string idField;
        
        private string idPromo_PromocionField;
        
        private string descripcionField;
        
        private string unidadConversionField;
        
        private string maximoField;
        
        private string saldoField;
        
        private string cantidad1Field;
        
        private string codigoIntField;
        
        private string listaHotelesField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string idPromo_Promocion {
            get {
                return this.idPromo_PromocionField;
            }
            set {
                this.idPromo_PromocionField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string UnidadConversion {
            get {
                return this.unidadConversionField;
            }
            set {
                this.unidadConversionField = value;
            }
        }
        
        /// <remarks/>
        public string Maximo {
            get {
                return this.maximoField;
            }
            set {
                this.maximoField = value;
            }
        }
        
        /// <remarks/>
        public string Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
        
        /// <remarks/>
        public string Cantidad1 {
            get {
                return this.cantidad1Field;
            }
            set {
                this.cantidad1Field = value;
            }
        }
        
        /// <remarks/>
        public string CodigoInt {
            get {
                return this.codigoIntField;
            }
            set {
                this.codigoIntField = value;
            }
        }
        
        /// <remarks/>
        public string ListaHoteles {
            get {
                return this.listaHotelesField;
            }
            set {
                this.listaHotelesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class GuardaPromocionForzadaResponse {
        
        private string messageField;
        
        private bool hasErrorsField;
        
        private string errorInfoField;
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool hasErrors {
            get {
                return this.hasErrorsField;
            }
            set {
                this.hasErrorsField = value;
            }
        }
        
        /// <remarks/>
        public string errorInfo {
            get {
                return this.errorInfoField;
            }
            set {
                this.errorInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class GuardaPromocionForzadaRequest {
        
        private string hotelField;
        
        private string folioField;
        
        private string adicionalField;
        
        private string idpromoField;
        
        private string usraltaField;
        
        private System.DateTime fechaaltaField;
        
        private string giftIDField;
        
        private string giftsReceiptIDField;
        
        private string idtipoasignacionField;
        
        private string statusField;
        
        private string usrmodifField;
        
        private System.DateTime fechamodifField;
        
        private string tipomovField;
        
        private float montoField;
        
        /// <remarks/>
        public string hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string adicional {
            get {
                return this.adicionalField;
            }
            set {
                this.adicionalField = value;
            }
        }
        
        /// <remarks/>
        public string idpromo {
            get {
                return this.idpromoField;
            }
            set {
                this.idpromoField = value;
            }
        }
        
        /// <remarks/>
        public string usralta {
            get {
                return this.usraltaField;
            }
            set {
                this.usraltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime fechaalta {
            get {
                return this.fechaaltaField;
            }
            set {
                this.fechaaltaField = value;
            }
        }
        
        /// <remarks/>
        public string GiftID {
            get {
                return this.giftIDField;
            }
            set {
                this.giftIDField = value;
            }
        }
        
        /// <remarks/>
        public string GiftsReceiptID {
            get {
                return this.giftsReceiptIDField;
            }
            set {
                this.giftsReceiptIDField = value;
            }
        }
        
        /// <remarks/>
        public string idtipoasignacion {
            get {
                return this.idtipoasignacionField;
            }
            set {
                this.idtipoasignacionField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string usrmodif {
            get {
                return this.usrmodifField;
            }
            set {
                this.usrmodifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime fechamodif {
            get {
                return this.fechamodifField;
            }
            set {
                this.fechamodifField = value;
            }
        }
        
        /// <remarks/>
        public string tipomov {
            get {
                return this.tipomovField;
            }
            set {
                this.tipomovField = value;
            }
        }
        
        /// <remarks/>
        public float monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class ActualizaEstatusPromoForzadaResponse {
        
        private string messageField;
        
        private bool hasErrorsField;
        
        private string errorInfoField;
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool hasErrors {
            get {
                return this.hasErrorsField;
            }
            set {
                this.hasErrorsField = value;
            }
        }
        
        /// <remarks/>
        public string errorInfo {
            get {
                return this.errorInfoField;
            }
            set {
                this.errorInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class ActualizaEstatusPromoForzadaRequest {
        
        private string hotelField;
        
        private string folioField;
        
        private string promoField;
        
        private string estatusField;
        
        /// <remarks/>
        public string hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        public string promo {
            get {
                return this.promoField;
            }
            set {
                this.promoField = value;
            }
        }
        
        /// <remarks/>
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class PromoForzadaFolioTipoResponse {
        
        private string hotelField;
        
        private string folioField;
        
        private string tipo_promoField;
        
        private string adicionalField;
        
        private string usraltaField;
        
        private System.DateTime fechaaltaField;
        
        private string idtipoasignacionField;
        
        private string statusField;
        
        private string usrmodifField;
        
        private System.DateTime fechamodifField;
        
        private string tipomovField;
        
        private float montoField;
        
        private string hotelnewField;
        
        private string folionewField;
        
        private string usrtransfField;
        
        private System.DateTime fechatransfField;
        
        private bool hasErrorsField;
        
        private string errorInfoField;
        
        /// <remarks/>
        public string hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        public string tipo_promo {
            get {
                return this.tipo_promoField;
            }
            set {
                this.tipo_promoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string adicional {
            get {
                return this.adicionalField;
            }
            set {
                this.adicionalField = value;
            }
        }
        
        /// <remarks/>
        public string usralta {
            get {
                return this.usraltaField;
            }
            set {
                this.usraltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime fechaalta {
            get {
                return this.fechaaltaField;
            }
            set {
                this.fechaaltaField = value;
            }
        }
        
        /// <remarks/>
        public string idtipoasignacion {
            get {
                return this.idtipoasignacionField;
            }
            set {
                this.idtipoasignacionField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string usrmodif {
            get {
                return this.usrmodifField;
            }
            set {
                this.usrmodifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime fechamodif {
            get {
                return this.fechamodifField;
            }
            set {
                this.fechamodifField = value;
            }
        }
        
        /// <remarks/>
        public string tipomov {
            get {
                return this.tipomovField;
            }
            set {
                this.tipomovField = value;
            }
        }
        
        /// <remarks/>
        public float monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string hotelnew {
            get {
                return this.hotelnewField;
            }
            set {
                this.hotelnewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string folionew {
            get {
                return this.folionewField;
            }
            set {
                this.folionewField = value;
            }
        }
        
        /// <remarks/>
        public string usrtransf {
            get {
                return this.usrtransfField;
            }
            set {
                this.usrtransfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime fechatransf {
            get {
                return this.fechatransfField;
            }
            set {
                this.fechatransfField = value;
            }
        }
        
        /// <remarks/>
        public bool hasErrors {
            get {
                return this.hasErrorsField;
            }
            set {
                this.hasErrorsField = value;
            }
        }
        
        /// <remarks/>
        public string errorInfo {
            get {
                return this.errorInfoField;
            }
            set {
                this.errorInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class PromoForzadaFolioTipoRequest {
        
        private string hotelField;
        
        private string folioField;
        
        private string tipoPromoField;
        
        /// <remarks/>
        public string hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        public string tipoPromo {
            get {
                return this.tipoPromoField;
            }
            set {
                this.tipoPromoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class PromocionesTipoResponse {
        
        private string recnumField;
        
        private string claveField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string estatusField;
        
        private string tipo_promoField;
        
        private System.DateTime book_iniField;
        
        private System.DateTime book_finField;
        
        private System.DateTime stay_iniField;
        
        private System.DateTime stay_finField;
        
        private bool incl_overField;
        
        private string stay_minField;
        
        private string stay_maxField;
        
        private string hoteles_siField;
        
        private string notaField;
        
        private System.DateTime ent_dateField;
        
        private string ent_timeField;
        
        private string ent_operField;
        
        private string ent_termField;
        
        private System.DateTime chg_dateField;
        
        private string chg_timeField;
        
        private string chg_operField;
        
        private string chg_termField;
        
        private float cargo_usdField;
        
        private string bill_toField;
        
        private bool in_folioField;
        
        private string cargo_codeField;
        
        private string promoField;
        
        private bool arv_basedField;
        
        private string emitida_porField;
        
        private string aplica_textField;
        
        private string noaplica_textField;
        
        private string gruposField;
        
        private string clubField;
        
        private string bill_freqField;
        
        private float cargo_usd2Field;
        
        private string bill_to2Field;
        
        private string cargo_code2Field;
        
        private bool front_applyField;
        
        private string pameField;
        
        private string pplusField;
        
        private string webField;
        
        private bool con_limitesField;
        
        private string productoField;
        
        private string desc_clienteField;
        
        private float costo_adultoField;
        
        private float costo_menorField;
        
        private string mostrar_cartaField;
        
        private bool hasErrorsField;
        
        private string errorInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string recnum {
            get {
                return this.recnumField;
            }
            set {
                this.recnumField = value;
            }
        }
        
        /// <remarks/>
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        public string tipo_promo {
            get {
                return this.tipo_promoField;
            }
            set {
                this.tipo_promoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        [SoapIgnore]
        public System.DateTime book_ini {
            get {
                return this.book_iniField;
            }
            set {
                this.book_iniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        [SoapIgnore]
        public System.DateTime book_fin {
            get {
                return this.book_finField;
            }
            set {
                this.book_finField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        [SoapIgnore]
        public System.DateTime stay_ini {
            get {
                return this.stay_iniField;
            }
            set {
                this.stay_iniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        [SoapIgnore]
        public System.DateTime stay_fin {
            get {
                return this.stay_finField;
            }
            set {
                this.stay_finField = value;
            }
        }
        
        /// <remarks/>
        public bool incl_over {
            get {
                return this.incl_overField;
            }
            set {
                this.incl_overField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string stay_min {
            get {
                return this.stay_minField;
            }
            set {
                this.stay_minField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string stay_max {
            get {
                return this.stay_maxField;
            }
            set {
                this.stay_maxField = value;
            }
        }
        
        /// <remarks/>
        public string hoteles_si {
            get {
                return this.hoteles_siField;
            }
            set {
                this.hoteles_siField = value;
            }
        }
        
        /// <remarks/>
        public string nota {
            get {
                return this.notaField;
            }
            set {
                this.notaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime ent_date {
            get {
                return this.ent_dateField;
            }
            set {
                this.ent_dateField = value;
            }
        }
        
        /// <remarks/>
        public string ent_time {
            get {
                return this.ent_timeField;
            }
            set {
                this.ent_timeField = value;
            }
        }
        
        /// <remarks/>
        public string ent_oper {
            get {
                return this.ent_operField;
            }
            set {
                this.ent_operField = value;
            }
        }
        
        /// <remarks/>
        public string ent_term {
            get {
                return this.ent_termField;
            }
            set {
                this.ent_termField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime chg_date {
            get {
                return this.chg_dateField;
            }
            set {
                this.chg_dateField = value;
            }
        }
        
        /// <remarks/>
        public string chg_time {
            get {
                return this.chg_timeField;
            }
            set {
                this.chg_timeField = value;
            }
        }
        
        /// <remarks/>
        public string chg_oper {
            get {
                return this.chg_operField;
            }
            set {
                this.chg_operField = value;
            }
        }
        
        /// <remarks/>
        public string chg_term {
            get {
                return this.chg_termField;
            }
            set {
                this.chg_termField = value;
            }
        }
        
        /// <remarks/>
        public float cargo_usd {
            get {
                return this.cargo_usdField;
            }
            set {
                this.cargo_usdField = value;
            }
        }
        
        /// <remarks/>
        public string bill_to {
            get {
                return this.bill_toField;
            }
            set {
                this.bill_toField = value;
            }
        }
        
        /// <remarks/>
        public bool in_folio {
            get {
                return this.in_folioField;
            }
            set {
                this.in_folioField = value;
            }
        }
        
        /// <remarks/>
        public string cargo_code {
            get {
                return this.cargo_codeField;
            }
            set {
                this.cargo_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string promo {
            get {
                return this.promoField;
            }
            set {
                this.promoField = value;
            }
        }
        
        /// <remarks/>
        public bool arv_based {
            get {
                return this.arv_basedField;
            }
            set {
                this.arv_basedField = value;
            }
        }
        
        /// <remarks/>
        public string emitida_por {
            get {
                return this.emitida_porField;
            }
            set {
                this.emitida_porField = value;
            }
        }
        
        /// <remarks/>
        public string aplica_text {
            get {
                return this.aplica_textField;
            }
            set {
                this.aplica_textField = value;
            }
        }
        
        /// <remarks/>
        public string noaplica_text {
            get {
                return this.noaplica_textField;
            }
            set {
                this.noaplica_textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string grupos {
            get {
                return this.gruposField;
            }
            set {
                this.gruposField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string club {
            get {
                return this.clubField;
            }
            set {
                this.clubField = value;
            }
        }
        
        /// <remarks/>
        public string bill_freq {
            get {
                return this.bill_freqField;
            }
            set {
                this.bill_freqField = value;
            }
        }
        
        /// <remarks/>
        public float cargo_usd2 {
            get {
                return this.cargo_usd2Field;
            }
            set {
                this.cargo_usd2Field = value;
            }
        }
        
        /// <remarks/>
        public string bill_to2 {
            get {
                return this.bill_to2Field;
            }
            set {
                this.bill_to2Field = value;
            }
        }
        
        /// <remarks/>
        public string cargo_code2 {
            get {
                return this.cargo_code2Field;
            }
            set {
                this.cargo_code2Field = value;
            }
        }
        
        /// <remarks/>
        public bool front_apply {
            get {
                return this.front_applyField;
            }
            set {
                this.front_applyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string pame {
            get {
                return this.pameField;
            }
            set {
                this.pameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string pplus {
            get {
                return this.pplusField;
            }
            set {
                this.pplusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
            }
        }
        
        /// <remarks/>
        public bool con_limites {
            get {
                return this.con_limitesField;
            }
            set {
                this.con_limitesField = value;
            }
        }
        
        /// <remarks/>
        public string producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
            }
        }
        
        /// <remarks/>
        public string desc_cliente {
            get {
                return this.desc_clienteField;
            }
            set {
                this.desc_clienteField = value;
            }
        }
        
        /// <remarks/>
        public float costo_adulto {
            get {
                return this.costo_adultoField;
            }
            set {
                this.costo_adultoField = value;
            }
        }
        
        /// <remarks/>
        public float costo_menor {
            get {
                return this.costo_menorField;
            }
            set {
                this.costo_menorField = value;
            }
        }
        
        /// <remarks/>
        public string mostrar_carta {
            get {
                return this.mostrar_cartaField;
            }
            set {
                this.mostrar_cartaField = value;
            }
        }
        
        /// <remarks/>
        public bool hasErrors {
            get {
                return this.hasErrorsField;
            }
            set {
                this.hasErrorsField = value;
            }
        }
        
        /// <remarks/>
        public string errorInfo {
            get {
                return this.errorInfoField;
            }
            set {
                this.errorInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class PromocionesTipoRequest {
        
        private string tipoPromoField;
        
        private string estatusField;
        
        /// <remarks/>
        public string tipoPromo {
            get {
                return this.tipoPromoField;
            }
            set {
                this.tipoPromoField = value;
            }
        }
        
        /// <remarks/>
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class OstdtpromosResponse {
        
        private string rmhotelField;
        
        private string rmfolioField;
        
        private string folvtaField;
        
        private string establecField;
        
        private string operacionField;
        
        private string servicioField;
        
        private string statusField;
        
        private float montoField;
        
        private string idpromoField;
        
        private string sistemaField;
        
        private System.DateTime fechamovField;
        
        private System.DateTime horamovField;
        
        private string codbeneficioField;
        
        private bool abonoforzadoField;
        
        private string idareaabonoforzadoField;
        
        private string usrabonoforzadoField;
        
        private string observacionesField;
        
        /// <remarks/>
        public string rmhotel {
            get {
                return this.rmhotelField;
            }
            set {
                this.rmhotelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string rmfolio {
            get {
                return this.rmfolioField;
            }
            set {
                this.rmfolioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string folvta {
            get {
                return this.folvtaField;
            }
            set {
                this.folvtaField = value;
            }
        }
        
        /// <remarks/>
        public string establec {
            get {
                return this.establecField;
            }
            set {
                this.establecField = value;
            }
        }
        
        /// <remarks/>
        public string operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
            }
        }
        
        /// <remarks/>
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public float monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string idpromo {
            get {
                return this.idpromoField;
            }
            set {
                this.idpromoField = value;
            }
        }
        
        /// <remarks/>
        public string sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        [SoapIgnore] 
        public System.DateTime fechamov {
            get {
                return this.fechamovField;
            }
            set {
                this.fechamovField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType ="date")]
        [SoapIgnore]
        public System.DateTime horamov {
            get {
                return this.horamovField;
            }
            set {
                this.horamovField = value;
            }
        }
        
        /// <remarks/>
        public string codbeneficio {
            get {
                return this.codbeneficioField;
            }
            set {
                this.codbeneficioField = value;
            }
        }
        
        /// <remarks/>
        public bool abonoforzado {
            get {
                return this.abonoforzadoField;
            }
            set {
                this.abonoforzadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string idareaabonoforzado {
            get {
                return this.idareaabonoforzadoField;
            }
            set {
                this.idareaabonoforzadoField = value;
            }
        }
        
        /// <remarks/>
        public string usrabonoforzado {
            get {
                return this.usrabonoforzadoField;
            }
            set {
                this.usrabonoforzadoField = value;
            }
        }
        
        /// <remarks/>
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class OstdtpromosRequest {
        
        private string hotelField;
        
        private string folioField;
        
        private string folvtaField;
        
        private string establecField;
        
        private string operacionField;
        
        private string servicioField;
        
        private float montoField;
        
        private string idpromoField;
        
        private string sistemaField;
        
        /// <remarks/>
        public string hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string folvta {
            get {
                return this.folvtaField;
            }
            set {
                this.folvtaField = value;
            }
        }
        
        /// <remarks/>
        public string establec {
            get {
                return this.establecField;
            }
            set {
                this.establecField = value;
            }
        }
        
        /// <remarks/>
        public string operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
            }
        }
        
        /// <remarks/>
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <remarks/>
        public float monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string idpromo {
            get {
                return this.idpromoField;
            }
            set {
                this.idpromoField = value;
            }
        }
        
        /// <remarks/>
        public string sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PromocionesControllerwsdl")]
    public partial class OstpromosResponse {
        
        private string rmhotelField;
        
        private string rmfolioField;
        
        private float creddispField;
        
        private float credusadoField;
        
        private string idpromoField;
        
        private int esResortCreditField;
        
        private string statusField;
        
        /// <remarks/>
        public string rmhotel {
            get {
                return this.rmhotelField;
            }
            set {
                this.rmhotelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string rmfolio {
            get {
                return this.rmfolioField;
            }
            set {
                this.rmfolioField = value;
            }
        }
        
        /// <remarks/>
        public float creddisp {
            get {
                return this.creddispField;
            }
            set {
                this.creddispField = value;
            }
        }
        
        /// <remarks/>
        public float credusado {
            get {
                return this.credusadoField;
            }
            set {
                this.credusadoField = value;
            }
        }
        
        /// <remarks/>
        public string idpromo {
            get {
                return this.idpromoField;
            }
            set {
                this.idpromoField = value;
            }
        }
        
        /// <remarks/>
        public int esResortCredit {
            get {
                return this.esResortCreditField;
            }
            set {
                this.esResortCreditField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ObtenerCabeceraEstadoCuentaCompletedEventHandler(object sender, ObtenerCabeceraEstadoCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCabeceraEstadoCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCabeceraEstadoCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OstpromosResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OstpromosResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ObtenerDetalleEstadoCuentaCompletedEventHandler(object sender, ObtenerDetalleEstadoCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDetalleEstadoCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDetalleEstadoCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OstdtpromosResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OstdtpromosResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ObtenerPromocionesTipoCompletedEventHandler(object sender, ObtenerPromocionesTipoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPromocionesTipoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPromocionesTipoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PromocionesTipoResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PromocionesTipoResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ObtenerPromocionesForzadasFolioTipoCompletedEventHandler(object sender, ObtenerPromocionesForzadasFolioTipoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPromocionesForzadasFolioTipoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPromocionesForzadasFolioTipoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PromoForzadaFolioTipoResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PromoForzadaFolioTipoResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ActualizaEstatusPromoForzadaFolioCompletedEventHandler(object sender, ActualizaEstatusPromoForzadaFolioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizaEstatusPromoForzadaFolioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizaEstatusPromoForzadaFolioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActualizaEstatusPromoForzadaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActualizaEstatusPromoForzadaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GuardarPromocionForzadaCompletedEventHandler(object sender, GuardarPromocionForzadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarPromocionForzadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarPromocionForzadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GuardaPromocionForzadaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GuardaPromocionForzadaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ObtenerBeneficiosByFolioCompletedEventHandler(object sender, ObtenerBeneficiosByFolioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerBeneficiosByFolioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerBeneficiosByFolioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BeneficiosxFolioResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BeneficiosxFolioResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultarPromocionesConsumidasCompletedEventHandler(object sender, ConsultarPromocionesConsumidasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPromocionesConsumidasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPromocionesConsumidasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsumosPromocionesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsumosPromocionesResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591